import { period,timeEvidence,unknownTime,contentHash } from './core.mjs'
import { seriesMetadata } from '../../../src/data/seriesContract.js'
import { pointAvailability,isRetrospective } from './alignment.mjs'
export function rawRecord(id,source,snapshot,status,points,request,config,{role=null,transform=null,transformed=[],supplemental=[],state='CONTEXT_ONLY',operand=false}={}) {
 const m=source.contract||seriesMetadata(source),last=points.at(-1),op=period(last.date,source.frequency,last.sourcePeriod,source.periodBasis)
 return {id,seriesId:source.id,sourceSeriesKey:source.sourceKey||source.id,datasetId:snapshot.datasetId,publisher:m.publisher,sourceUrl:m.sourceUrl,snapshotId:snapshot.id,inputVintageId:snapshot.inputVintageId,snapshotSha256:snapshot.snapshotSha256,frequency:source.frequency,units:m.units,denominator:source.denominator||null,maintenanceType:m.automationType,dependencyRole:role||config.ownership[source.id].dependencyRole,observationPeriod:op,rawValue:last.value,sourceUpdatedAt:timeEvidence(source.sourceUpdatedTime||source.sourceUpdatedAt,'Source/distributor vintage update; not initial publication of old rows'),retrievedAt:timeEvidence(source.retrievedAt,'Repository retrieval metadata; not completion proof'),firstSeenAt:snapshot.firstSeenAt||null,snapshotAcceptedAt:snapshot.snapshotAcceptedAt,availableAt:isRetrospective(request)?null:pointAvailability(source,last,snapshot),availabilityBasis:isRetrospective(request)?'NOT_RECONSTRUCTED':'PROJECT_ACCEPTED_SNAPSHOT',validUntil:status.validUntil||null,validUntilInclusive:status.validUntilInclusive??null,freshnessState:status.state,freshnessPolicyRef:operand?'WINDOW_OPERAND_SOURCE_SNAPSHOT':`PINNED_V0_13:${source.id}`,inputObservations:points.map(p=>({observationPeriod:period(p.date,source.frequency,p.sourcePeriod,source.periodBasis),value:p.value,availableAt:isRetrospective(request)?null:pointAvailability(source,p,snapshot),availabilityBasis:isRetrospective(request)?'NOT_RECONSTRUCTED':'PROJECT_ACCEPTED_SNAPSHOT',releasePublishedAt:p.releasePublishedAt||unknownTime(),revisionEventIds:p.revisionEventIds||[]})),operandEvidenceIds:[],transform:transform||{id:null,parameters:{},value:null,units:null},state,ruleId:config.ruleVersion,revisionEventIds:[...new Set(points.flatMap(p=>p.revisionEventIds||[]))],qualityFlags:[],limitations:[source.definition||'Source definition retained in canonical repository snapshot',source.qualifier?`Publication qualifier: ${source.qualifier}`:'No inferred causal effect'],methodologyRef:null,transformedWindow:transformed,supplementalMeasurements:supplemental}
}
export function derivedRecord(id,spec,operands,value,op,boundary,request,config) {
 const times=operands.map(p=>p.availableAt)
 const available=isRetrospective(request)||times.some(t=>!t)?null:new Date(Math.max(...times.map(Date.parse))).toISOString()
 return {id,seriesId:spec.outputSeriesId,sourceSeriesKey:null,datasetId:`derived:${id}`,publisher:'World Inflation Lens arithmetic',sourceUrl:null,snapshotId:null,inputVintageId:`derived:${contentHash({id,ruleVersion:config.ruleVersion,operands})}`,snapshotSha256:null,frequency:op.kind==='quarter'?'quarterly':op.kind==='day'?'daily':'annual',units:spec.units,denominator:null,maintenanceType:'DERIVED',dependencyRole:spec.role,observationPeriod:op,rawValue:null,sourceUpdatedAt:unknownTime(),retrievedAt:unknownTime(),firstSeenAt:null,snapshotAcceptedAt:null,availableAt:available,availabilityBasis:isRetrospective(request)?'NOT_RECONSTRUCTED':'PROJECT_ACCEPTED_SNAPSHOT',validUntil:boundary.validUntil,validUntilInclusive:boundary.validUntilInclusive,freshnessState:isRetrospective(request)?'NOT_RECONSTRUCTED':'DERIVED',freshnessPolicyRef:`DERIVED_ENDPOINT:${id}`,inputObservations:[],operandEvidenceIds:operands.map(p=>p.id),transform:{id,parameters:{operation:spec.operation},value,units:spec.units},state:'CONTEXT_ONLY',ruleId:config.ruleVersion,revisionEventIds:[...new Set(operands.flatMap(p=>p.revisionEventIds))],qualityFlags:[],limitations:['Arithmetic context; no additional primary vote'],methodologyRef:id,transformedWindow:[],supplementalMeasurements:[]}
}
