export const statusCopy = {
  en: {
    title:'System Status', intro:'Application, data checks, deployment and email have independent outcomes. Times shown in UTC; date/month-only source fields retain their original precision.',
    application:'Application',version:'Version',code:'Code commit',snapshot:'Snapshot commit',pipeline:'Data pipeline',started:'Last check started',completed:'Last check completed',successful:'Last successful check completed',legacy:'Legacy successful-check record (completion time unavailable)',attempt:'Last workflow attempt',refresh:'Refresh result',deployment:'Deployment',deployed:'Last successful deployment',notification:'Notification',unknown:'Unknown / not recorded',unavailable:'Live status unavailable; the validated built snapshot remains available.',live:'Independent status artifact checked',built:'Displayed application build',mismatch:'The latest recorded deployment differs from this browser build. Reload to check the current website.',
    actions:'View workflow outcomes',accepted:'Gmail accepted the message. Inbox delivery is not verified.',failed:'Latest refresh attempt failed; displayed data remain the prior validated snapshot.',aggregate:'Evidence states at the last successful deployment (counts, not a score)',
    observation:'Latest observation',updated:'Source updated',retrieved:'Retrieved / imported',reviewed:'Last manually reviewed',automation:'Evidence maintenance',expected:'Expected normal source release',due:'Distribution grace ends',rule:'Freshness rule',vintage:'Reviewed forecast vintage',published:'Forecast publication',source:'Source schedule',
    states:{CURRENT:'Current within the documented window',CHECKED_NO_NEW_RELEASE:'Checked — no observation change',WAITING_FOR_EXPECTED_RELEASE:'Waiting for normal release / distribution',SOURCE_UPDATED_NOT_YET_CAPTURED:'Newer source metadata not yet captured',STALE:'Expected window exceeded — check source',REFRESH_FAILED:'Refresh failed — previous data retained',MANUAL_REVIEWED:'Manually reviewed evidence',MANUAL_REVIEW_REQUIRED:'Manual review due',FIXED_VINTAGE:'Fixed reviewed forecast vintage',STATIC:'Static reference — not freshness-scored',DERIVED:'Derived — check input series',PLANNED:'Planned — no integrated data',UNKNOWN:'Freshness unknown'},
    results:{SUCCESS_CHANGED:'Successful — observations changed',SUCCESS_NO_CHANGE:'Successful — no observation changes',FAILED:'Failed',RUNNING:'In progress',NOT_REQUESTED:'Not requested',UNKNOWN:'Unknown / not recorded',success:'Succeeded',failure:'Failed',cancelled:'Cancelled',skipped:'Skipped',unknown:'Unknown / not recorded',ACCEPTED_BY_GMAIL:'Accepted by Gmail — delivery unverified',SKIPPED_NOT_CONFIGURED:'Skipped — not configured',FAILED_AUTH:'Failed — authentication',FAILED_TRANSPORT:'Failed — transport / acceptance uncertain',FAILED_CONFIGURATION:'Failed — configuration'},
    reasons:{normal_release_or_distribution_window:'Release calendars allow four hours for distribution; exceptional closures may differ.',expected_release_window_elapsed_not_proof_of_publication:'Normal expected publication window has elapsed. This does not prove that the provider has published.',matches_normal_release_window:'Matches the normal publication calendar; not a real-time quote.',successful_check_no_observation_change:'A successful check found no changed observation; this does not imply a newly published period.',within_conservative_lag_calendar_not_known:'Within a conservative period-based lag. The exact release day is not known.',conservative_period_lag_exceeded_not_official_deadline:'Conservative lag exceeded; this is not an official publication deadline.',manual_evidence_not_automatically_refreshed:'Automatic pipeline checks do not re-review this publication.',reviewed_forecast_vintage:'A conditional, separately reviewed forecast; ordinary daily freshness rules do not apply.',not_freshness_scored:'Static references are not freshness-scored.',assess_input_series_separately:'The underlying input dates and definitions determine availability.',validated_source_probe_is_newer:'A validated source check found metadata or coverage newer than this displayed snapshot.',prior_validated_snapshot_retained:'The latest data refresh failed; no invalid candidate was published.',missing_metadata_or_observation:'Metadata or observations are insufficient for a freshness assessment.',not_integrated:'No observed values are integrated.',unrecognized_period:'Source period could not be interpreted safely.'},
  },
  zh: {
    title:'系统状态',intro:'应用、数据检查、部署和邮件分别记录结果。时间戳显示 UTC；来源仅提供日期或月份时保留原精度。',
    application:'应用',version:'版本',code:'代码提交',snapshot:'快照提交',pipeline:'数据流程',started:'最近检查开始',completed:'最近检查完成',successful:'最近成功检查完成',legacy:'旧版成功检查记录（未记录完成时间）',attempt:'最近工作流尝试',refresh:'刷新结果',deployment:'部署',deployed:'最近成功部署',notification:'邮件通知',unknown:'未知／尚未记录',unavailable:'独立状态暂不可用；已验证的构建快照仍可查看。',live:'已读取独立状态记录',built:'当前浏览器中的应用构建',mismatch:'最新部署记录与当前浏览器构建不同，可刷新页面查看当前网站。',
    actions:'查看工作流结果',accepted:'Gmail 已接受邮件；不能据此确认邮件进入收件箱。',failed:'最近一次刷新失败；当前数据仍为此前已验证的快照。',aggregate:'最近成功部署时的证据状态（数量，不是评分）',
    observation:'最新观测',updated:'来源更新',retrieved:'抓取／导入',reviewed:'最近人工审核',automation:'证据维护方式',expected:'正常日历预计来源发布',due:'分发宽限窗口结束',rule:'新鲜度规则',vintage:'已审核预测版本',published:'预测发布日期',source:'来源发布说明',
    states:{CURRENT:'处于已说明的更新窗口内',CHECKED_NO_NEW_RELEASE:'已检查——观测值无变化',WAITING_FOR_EXPECTED_RELEASE:'等待正常发布／分发窗口',SOURCE_UPDATED_NOT_YET_CAPTURED:'来源元数据较新，尚未进入当前快照',STALE:'超过预计窗口——请核对来源',REFRESH_FAILED:'刷新失败——保留此前数据',MANUAL_REVIEWED:'人工审核资料',MANUAL_REVIEW_REQUIRED:'需要人工复核',FIXED_VINTAGE:'固定的已审核预测版本',STATIC:'静态资料——不评估新鲜度',DERIVED:'衍生指标——需查看输入数据',PLANNED:'规划中——尚无接入数据',UNKNOWN:'新鲜度未知'},
    results:{SUCCESS_CHANGED:'成功——观测有变化',SUCCESS_NO_CHANGE:'成功——观测无变化',FAILED:'失败',RUNNING:'进行中',NOT_REQUESTED:'本次未请求',UNKNOWN:'未知／尚未记录',success:'成功',failure:'失败',cancelled:'已取消',skipped:'已跳过',unknown:'未知／尚未记录',ACCEPTED_BY_GMAIL:'Gmail 已接受——收件箱投递未验证',SKIPPED_NOT_CONFIGURED:'已跳过——尚未配置',FAILED_AUTH:'失败——身份验证',FAILED_TRANSPORT:'失败——连接或接受状态不确定',FAILED_CONFIGURATION:'失败——配置'},
    reasons:{normal_release_or_distribution_window:'正常发布后预留四小时分发宽限；临时休市等情况可能不同。',expected_release_window_elapsed_not_proof_of_publication:'正常日历预计窗口已过；这并不证明来源实际已经发布。',matches_normal_release_window:'符合正常发布日历；不代表实时行情。',successful_check_no_observation_change:'成功检查未发现观测变化；不代表来源新发布了一个期间。',within_conservative_lag_calendar_not_known:'处于保守的期间滞后窗口内；未假定确切发布日期。',conservative_period_lag_exceeded_not_official_deadline:'超过本站保守滞后窗口；不是官方发布期限。',manual_evidence_not_automatically_refreshed:'自动流程的检查不会重新人工审核这份出版资料。',reviewed_forecast_vintage:'单独审核的条件预测；不使用普通日度新鲜度规则。',not_freshness_scored:'静态历史资料不评估新鲜度。',assess_input_series_separately:'可用性取决于各输入的观测日期与定义。',validated_source_probe_is_newer:'已验证的来源检查发现元数据或覆盖期间比当前显示快照更新。',prior_validated_snapshot_retained:'最近刷新失败；未发布无效候选数据。',missing_metadata_or_observation:'元数据或观测不足，无法判断。',not_integrated:'尚未接入观测值。',unrecognized_period:'无法安全识别来源期间。'},
  },
}
