export const copy = {
  en: {
    navigation: 'Main navigation', language: 'Language', footer: 'A clearer view of prices through time.', placeholderLabel: 'VISUALIZATION IN DEVELOPMENT',
    nav: { home: 'Home', overview: 'Overview', timeline: 'Timeline', 'us-cpi': 'U.S. CPI', map: 'World Map', drivers: 'Drivers', sources: 'Data Sources' },
    home: { eyebrow: 'UNDERSTANDING THE WORLD THROUGH PRICES', title: 'Inflation has a history.', titleAccent: 'See the bigger picture.', description: 'Explore how prices have changed across decades and borders. A starting point for understanding the forces behind inflation around the world.', explore: 'Explore inflation', timeline: 'View timeline', sectionEyebrow: 'EXPLORE THE LENS', sectionTitle: 'Different views. One story.', sectionDescription: 'Move between a global perspective, historical context, and focused visualizations.', features: [ { title: 'Global overview', description: 'Understand the patterns and questions that shape inflation worldwide.' }, { title: 'Historical timeline', description: 'Trace major episodes that changed the direction of prices.' }, { title: 'U.S. CPI', description: 'A dedicated space for long-run U.S. consumer price data.' }, { title: 'Global map', description: 'A future geographic view of inflation across countries.' } ] },
    overview: { eyebrow: '01 / GLOBAL PERSPECTIVE', title: 'Global Inflation Overview', description: 'Inflation is a shared global story, but every country experiences it differently. This overview frames the questions the data will answer.', frameworkEyebrow: 'THE FRAMEWORK', frameworkTitle: 'A lens for comparison', frameworkDescription: 'Future releases will connect consistent data series to these themes.', cards: [ { title: 'Across countries', description: 'Compare inflation rates while keeping differences in measurement and timing visible.' }, { title: 'Across decades', description: 'Place today’s price changes alongside earlier inflation cycles.' }, { title: 'Across causes', description: 'Explore the roles of energy, supply shocks, policy, and demand.' } ], notice: 'V0.1 establishes the structure. No live statistics are displayed yet.' },
    timeline: { eyebrow: '02 / HISTORICAL CONTEXT', title: 'Historical Inflation Timeline', description: 'A starting guide to major episodes in modern inflation history. Dates and descriptions are contextual markers, not a statistical series.', sectionEyebrow: 'SELECTED MILESTONES', sectionTitle: 'Inflation through time', sectionDescription: 'These events provide context for the datasets planned in later releases.', events: [ { year: '1970s', category: 'ENERGY & POLICY', title: 'Oil shocks and stagflation', description: 'Energy price shocks and persistent inflation reshaped economic policy in many countries.' }, { year: '1980s', category: 'MONETARY POLICY', title: 'Disinflation era', description: 'Tighter monetary policy helped bring inflation down in many advanced economies.' }, { year: '2008', category: 'GLOBAL CRISIS', title: 'Financial crisis', description: 'A global downturn changed demand, policy, and price dynamics.' }, { year: '2020–22', category: 'GLOBAL SHOCK', title: 'Pandemic and recovery', description: 'Supply disruptions and reopening demand contributed to a broad inflation surge.' } ], note: 'Historical summaries are illustrative. Event citations and linked datasets will be added in a later release.' },
    placeholders: { 'us-cpi': { eyebrow: '03 / UNITED STATES', title: 'U.S. Long-Term CPI', description: 'A home for exploring the long-run path of U.S. consumer prices and inflation.', panelTitle: 'The long view is coming.', panelDescription: 'This chart is a visual placeholder. It does not represent actual CPI observations.', nextStep: 'Planned: connect a documented FRED CPI series, with units, dates, and source attribution.' }, map: { eyebrow: '04 / AROUND THE WORLD', title: 'Global Inflation Map', description: 'A geographic view will help compare inflation across countries and regions.', panelTitle: 'A world of data awaits.', panelDescription: 'This map is a visual placeholder. No country values are shown in V0.1.', nextStep: 'Planned: connect comparable country indicators and explain coverage and missing data.' } },
    sources: { eyebrow: '05 / TRANSPARENCY', title: 'Data Sources', description: 'The providers and historical resources planned for this project. V0.1 does not fetch or display their data.', sectionEyebrow: 'SOURCE REGISTRY', sectionTitle: 'Built on open evidence', sectionDescription: 'Each future visualization will identify its exact series, units, date range, and update cadence.', visit: 'open source website', note: 'Listing a provider does not imply that its data has been integrated yet.' },
  },
  zh: {
    navigation: '主导航', language: '语言', footer: '以更清晰的视角观察价格变迁。', placeholderLabel: '可视化功能开发中',
    nav: { home: '首页', overview: '全球概览', timeline: '历史时间线', 'us-cpi': '美国 CPI', map: '全球地图', drivers: '通胀因素', sources: '数据来源' },
    home: { eyebrow: '透过价格理解世界', title: '通胀有其历史。', titleAccent: '看见更大的图景。', description: '探索数十年间、不同国家的价格变化。从这里开始，理解影响全球通胀的力量。', explore: '探索通胀', timeline: '查看时间线', sectionEyebrow: '探索不同视角', sectionTitle: '多种视角，同一个故事。', sectionDescription: '从全球趋势、历史背景到专题图表，逐步理解通胀。', features: [ { title: '全球概览', description: '了解塑造全球通胀的主要模式与问题。' }, { title: '历史时间线', description: '回顾改变价格走势的重要历史阶段。' }, { title: '美国 CPI', description: '为美国长期消费者价格数据预留的专题页面。' }, { title: '全球地图', description: '未来将以地理视角展示各国通胀。' } ] },
    overview: { eyebrow: '01 / 全球视角', title: '全球通胀概览', description: '通胀是全球共同面对的议题，但各国的经历并不相同。本页梳理未来数据将回答的问题。', frameworkEyebrow: '分析框架', frameworkTitle: '比较通胀的视角', frameworkDescription: '后续版本将为这些主题接入一致、可比的数据序列。', cards: [ { title: '跨国比较', description: '比较各国通胀率，同时说明统计口径与时间差异。' }, { title: '跨越年代', description: '把今天的价格变化放在过去的通胀周期中观察。' }, { title: '探究成因', description: '探索能源、供应冲击、政策与需求的作用。' } ], notice: 'V0.1 搭建页面结构，暂不展示实时统计数据。' },
    timeline: { eyebrow: '02 / 历史背景', title: '历史通胀时间线', description: '了解现代通胀史上的重要阶段。以下日期与描述仅供背景参考，并非统计数据序列。', sectionEyebrow: '重要节点', sectionTitle: '通胀的历史轨迹', sectionDescription: '这些事件为后续接入的数据集提供背景。', events: [ { year: '1970年代', category: '能源与政策', title: '石油冲击与滞胀', description: '能源价格冲击与持续通胀改变了许多国家的经济政策。' }, { year: '1980年代', category: '货币政策', title: '通胀回落时期', description: '更紧缩的货币政策帮助许多发达经济体降低通胀。' }, { year: '2008', category: '全球危机', title: '金融危机', description: '全球经济下行改变了需求、政策与价格走势。' }, { year: '2020–22', category: '全球冲击', title: '疫情与复苏', description: '供应中断与经济重启后的需求推动了广泛的通胀上升。' } ], note: '历史摘要仅作示意。事件引用与关联数据集将在后续版本补充。' },
    placeholders: { 'us-cpi': { eyebrow: '03 / 美国', title: '美国长期 CPI', description: '未来可在这里探索美国消费者价格和通胀的长期走势。', panelTitle: '长期走势，敬请期待。', panelDescription: '图形仅为视觉占位，不代表真实 CPI 观测值。', nextStep: '计划接入有完整说明的 FRED CPI 数据序列，并标注单位、日期和来源。' }, map: { eyebrow: '04 / 纵览世界', title: '全球通胀地图', description: '未来将通过地图比较不同国家和地区的通胀情况。', panelTitle: '全球数据，即将呈现。', panelDescription: '地图仅为视觉占位。V0.1 不展示任何国家的数值。', nextStep: '计划接入可比较的各国指标，并说明覆盖范围与缺失数据。' } },
    sources: { eyebrow: '05 / 透明度', title: '数据来源', description: '本项目计划使用的数据提供方和历史资料。V0.1 尚未获取或展示其数据。', sectionEyebrow: '来源目录', sectionTitle: '以公开证据为基础', sectionDescription: '未来每个可视化图表都会标明具体序列、单位、时间范围及更新频率。', visit: '打开来源网站', note: '列出提供方并不意味着其数据已经接入。' },
  },
}
