import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {plan,families,validateDocument,manualSeed,companyStates,classify,compare,qualify} from '../access/qualification.mjs';
import {bytes} from '../../scripts/contract.mjs';
const raw=Buffer.from('<html><body>Microsoft financial results Revenue quarter ended June 30, 2026</body></html>');
const digest=b=>createHash('sha256').update(b).digest('hex');
const s={company:'MSFT',kind:'html',periodEnd:'2026-06-30',sha256:digest(raw)};
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'wil-access-test-'));
const clock=()=>Date.parse('2026-10-07T12:00:00Z');
const stubValidate=(source,body)=>({result:'PASS',detail:'TEST_ONLY_VALID_DOCUMENT',documentQualified:true});
const responses=async url=>{
 if(url.includes('data.sec.gov'))return new Response('',{status:403});
 if(url.includes('www.sec.gov'))return new Response('',{status:403});
 if(url.includes('earnings/default'))return new Response('<html>Microsoft investor earnings <a href="https://www.microsoft.com/en-us/investor/earnings/fy-2026-q4/press-release-webcast">2026 earnings release</a></html>',{headers:{'Content-Type':'text/html'}});
 if(url.includes('abc.xyz')||url.includes('ir.aboutamazon.com')||url.includes('investor.atmeta.com'))return new Response('',{status:403});
 return new Response(raw,{headers:{'Content-Type':'text/html'}});
};
const run=opts=>qualify({runner:'LOCAL_MAC',asOf:'2026-10-07',cache:temp(),clock,sleep:async()=>{},validator:stubValidate,fetcher:responses,...opts});
test('all twelve matrix families have pinned or official endpoint controls',()=>{assert.equal(families.length,12);for(const f of families)assert.ok(plan().some(p=>p.family===f));});
test('six known financial controls have accepted hashes and period identity',()=>{const c=plan().filter(p=>p.sha256);assert.equal(c.length,6);for(const p of c){assert.match(p.sha256,/^[a-f0-9]{64}$/);assert.equal(p.periodEnd,'2026-06-30');}});
test('known historical HTML with exact hash passes',()=>assert.equal(validateDocument(s,raw,'text/html').detail,'PASS_EXISTING_HASH'));
test('200 challenge HTML cannot pass even with a matching hash',()=>{const b=Buffer.from('<html>Microsoft verify you are human June 30, 2026 earnings</html>');assert.equal(validateDocument({...s,sha256:digest(b)},b,'text/html').result,'LAYOUT_UNSUPPORTED');});
test('MIME mismatch rejected',()=>assert.equal(validateDocument(s,raw,'application/pdf').result,'CONTENT_TYPE_REJECTED'));
test('issuer mismatch rejected',()=>assert.equal(validateDocument({...s,company:'GOOG'},raw,'text/html').detail,'ISSUER_MISMATCH'));
test('period mismatch rejected',()=>assert.equal(validateDocument({...s,periodEnd:'2026-09-30'},raw,'text/html').detail,'PERIOD_MISMATCH'));
test('changed known document stays review-required',()=>assert.equal(validateDocument({...s,sha256:'a'.repeat(64)},raw,'text/html').detail,'CHANGED_BYTES_REVIEW_REQUIRED'));
test('unhashed manual document does not qualify a runner',()=>assert.equal(validateDocument({...s,sha256:undefined},raw,'text/html').documentQualified,false));
test('empty or unsupported HTML rejected',()=>assert.equal(validateDocument(s,Buffer.from(''),'text/html').result,'LAYOUT_UNSUPPORTED'));
test('PDF magic required despite PDF MIME',()=>assert.equal(validateDocument({...s,kind:'pdf'},raw,'application/pdf').result,'CONTENT_TYPE_REJECTED'));
test('XLSX magic required despite workbook MIME',()=>assert.equal(validateDocument({...s,kind:'xlsx'},raw,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').result,'CONTENT_TYPE_REJECTED'));
test('manual known delegated seed uses frozen issuer delegation',()=>{const p=plan().find(p=>p.family==='GOOG_CDN');assert.equal(manualSeed({company:'GOOG',url:p.url,expectedQuarter:'2026Q2'}).sha256,p.sha256);});
test('manual wrong host rejected',()=>assert.throws(()=>manualSeed({company:'MSFT',url:'https://example.org/a.pdf',expectedQuarter:'2026Q3'})));
test('manual CDN wrong tenant rejected',()=>assert.throws(()=>manualSeed({company:'META',url:'https://s21.q4cdn.com/999/files/a.pdf',expectedQuarter:'2026Q3'})));
test('manual insecure URL rejected',()=>assert.throws(()=>manualSeed({company:'MSFT',url:'http://www.microsoft.com/a.pdf',expectedQuarter:'2026Q3'})));
test('manual malformed quarter rejected',()=>assert.throws(()=>manualSeed({company:'MSFT',url:'https://www.microsoft.com/a.pdf',expectedQuarter:'2026Q9'})));
test('SEC blocked, issuer control fetch qualified; failures remain independent',async()=>{const r=await run();assert.equal(r.companies.MSFT.secStatus,'ACCESS_BLOCKED');for(const c of ['MSFT','GOOG','AMZN','META'])assert.equal(r.companies[c].documentFetchStatus,'DOCUMENT_FETCH_QUALIFIED');});
test('discovery blocked and document qualified stay separate',async()=>{const r=await run();assert.equal(r.companies.GOOG.discoveryStatus,'DISCOVERY_ACCESS_BLOCKED');assert.equal(r.companies.GOOG.documentFetchStatus,'DOCUMENT_FETCH_QUALIFIED');assert.equal(r.classification,'PARTIALLY_QUALIFIED');});
test('403 host is not requested repeatedly in the same run',async()=>{let calls=0;await run({fetcher:async(u,o)=>{if(u.includes('data.sec.gov'))calls++;return responses(u,o);}});assert.equal(calls,1);});
test('429 Retry-After preserved without retry',async()=>{let calls=0;const src=plan().filter(p=>p.family==='SEC_SUBMISSIONS');const r=await run({sources:src,fetcher:async()=>{calls++;return new Response('',{status:429,headers:{'Retry-After':'120'}});}});assert.equal(calls,1);assert.equal(r.probes[0].http.retryAfter,'120');});
test('unofficial redirect rejected before second network request',async()=>{let calls=0;const r=await run({sources:plan().slice(0,1),fetcher:async()=>{calls++;return new Response('',{status:302,headers:{location:'https://evil.example/a'}});}});assert.equal(calls,1);assert.equal(r.probes[0].result,'REDIRECT_REJECTED');});
test('archive HTTP 200 without qualified links is not discovery PASS',async()=>{const r=await run({sources:plan().filter(p=>p.family==='MSFT_IR'),fetcher:async()=>new Response('<html>Microsoft investor earnings</html>',{headers:{'content-type':'text/html'}})});assert.equal(r.probes[0].result,'NO_STATIC_LINK');assert.equal(r.companies.MSFT.discoveryStatus,'DISCOVERY_UNQUALIFIED');});
test('discovery qualified while financial documents blocked is not primary',async()=>{const r=await run({sources:plan().filter(p=>['GOOG_IR','GOOG_CDN'].includes(p.family)),fetcher:async u=>u.includes('s206.q4cdn.com')?new Response('',{status:403}):new Response('<html>Alphabet investor earnings <a href="https://s206.q4cdn.com/479360582/files/doc_financials/2026/q2/2026q2-alphabet-earnings-release.pdf">2026 earnings release</a></html>',{headers:{'content-type':'text/html'}})});assert.equal(r.companies.GOOG.discoveryStatus,'DISCOVERY_QUALIFIED');assert.equal(r.companies.GOOG.coreFinancialDocumentStatus,'UNQUALIFIED');assert.equal(r.classification,'PARTIALLY_QUALIFIED');});
test('invalid SEC issuer/schema is not NO_NEW_DISCLOSURE',async()=>{const r=await run({sources:plan().filter(p=>p.family==='SEC_SUBMISSIONS'),fetcher:async()=>new Response(JSON.stringify({cik:123}),{headers:{'content-type':'application/json'}})});assert.equal(r.probes[0].result,'LAYOUT_UNSUPPORTED');assert.equal(r.probes[0].currentDiscovery,undefined);});
test('explicit current clock required',async()=>assert.rejects(run({asOf:'2026-10-06'}),/EXPLICIT_CURRENT_RUN_CLOCK/));
test('impossible cutoff date rejected',async()=>assert.rejects(run({asOf:'2026-02-30'}),/DATE/));
test('raw cache cannot be stored in the checkout',async()=>assert.rejects(run({cache:process.cwd()}),/EXTERNAL_CACHE_REQUIRED/));
const complete=Object.fromEntries(['MSFT','GOOG','AMZN','META'].map(c=>[c,{discoveryStatus:'DISCOVERY_QUALIFIED',coreFinancialDocumentStatus:'QUALIFIED',documentFetchStatus:'DOCUMENT_FETCH_QUALIFIED'}]));
test('all four discovery and core fetch routes required for primary',()=>{assert.equal(classify(complete),'QUALIFIED_PRIMARY_RUNNER');assert.equal(classify({...complete,META:{...complete.META,discoveryStatus:'DISCOVERY_UNQUALIFIED'}}),'PARTIALLY_QUALIFIED');});
test('qualified split-runner strategy requires coverage for every company',()=>{const a={...complete,META:{discoveryStatus:'DISCOVERY_UNQUALIFIED',coreFinancialDocumentStatus:'UNQUALIFIED'}};const b=Object.fromEntries(Object.entries(complete).map(([c,v])=>[c,c==='META'?v:{discoveryStatus:'DISCOVERY_UNQUALIFIED',coreFinancialDocumentStatus:'UNQUALIFIED'}]));const r=compare([{runner:{type:'A'},classification:'PARTIALLY_QUALIFIED',companies:a},{runner:{type:'B'},classification:'PARTIALLY_QUALIFIED',companies:b}]);assert.equal(r.splitRunnerQualified,true);assert.equal(compare([{runner:{type:'A'},companies:a}]).primary,null);assert.match(compare([{runner:{type:'A'},companies:a}]).decision,/REQUIRES REPAIR/);});
test('empty evidence cannot qualify a runner',()=>assert.equal(classify(companyStates([])),'UNQUALIFIED'));
test('fixed compact report serializes deterministically',()=>{const r={baseSHA:'x',matrix:families,runner:{startedAt:'2026-10-07T12:00:00Z'}};assert.equal(bytes(r),bytes(JSON.parse(bytes(r))));});
test('fresh-process control plan bytes reproduce',()=>{const code="import {plan} from './research/ai-capex-monetization/refresh/access/qualification.mjs'; console.log(JSON.stringify(plan()));";assert.equal(execFileSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8'}).toString(),execFileSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8'}).toString());});
test('identical fixtures have identical access identity despite run timing',async()=>{const a=await run(),b=await run();assert.equal(a.accessIdentity,b.accessIdentity);assert.equal(a.economicIdentityGenerated,false);assert.equal(a.acceptedDataPromotion,false);});
const workflow=fs.readFileSync('.github/workflows/ai-capex-access-qualification.yml','utf8');
test('workflow dispatch only; read permissions, no stored credentials',()=>{assert.match(workflow,/workflow_dispatch:/);assert.match(workflow,/contents: read/);assert.match(workflow,/persist-credentials: false/);assert.doesNotMatch(workflow,/schedule:|cron:|pull_request:|push:|contents: write|id-token:|pages:/);});
test('workflow uploads only compact report, no cache or raw documents',()=>assert.match(workflow,/path: .*access-report\.json/));
test('no accepted promotion, production writes, email or LLM dependency',()=>{const source=fs.readFileSync('research/ai-capex-monetization/refresh/access/qualification.mjs','utf8');assert.doesNotMatch(source,/nodemailer|openai|anthropic|sendMail|--promote/);assert.match(source,/economicIdentityGenerated:false/);assert.match(source,/acceptedDataPromotion:false/);assert.doesNotMatch(workflow,/git push|deploy-pages|notify|npm run data:refresh/);});

test('research dispatch bridge excludes Signal job and grants no extra permissions',()=>{const bridge=fs.readFileSync('.github/workflows/signal-engine-shadow-qualification.yml','utf8');const original=bridge.split('  ai-capex-access:')[0];assert.match(original,/refs\/heads\/codex\/signal-engine-production-pipeline/);assert.doesNotMatch(original,/refs\/heads\/codex\/ai-capex-live-runner-access/);assert.match(bridge,/ai-capex-access:[\s\S]*if: github.ref == 'refs\/heads\/codex\/ai-capex-live-runner-access'/);assert.doesNotMatch(bridge,/schedule:|contents: write|deploy-pages|sendMail|git push/);});
