import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {hash,bytes} from '../../scripts/contract.mjs';import {companies} from '../scripts/config.mjs';import {sha256} from '../../quarterly/scripts/retrieve.mjs';
import {SafeFetcher,permitted,putObject,cacheObject} from '../scripts/fetch.mjs';import {submissions,archiveLinks,detectSourceChanges} from '../scripts/discovery.mjs';
import {quarter,timestamp,bindDefinitions,validateRows,reconstruct,selectQuarter,qualifyQuarter,detectRestatements,qualifySource} from '../scripts/qualify.mjs';
import {candidateMonitor,candidatePreview,validateCandidate,promotionGate} from '../scripts/monitor.mjs';import {refresh} from '../scripts/run.mjs';import {fixture,data,clone,index,clock} from './helpers.mjs';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'wil-phase2d-test-'));
function fetcher(fn,cache=temp()){return new SafeFetcher({cache,fetcher:fn,clock,sleep:async()=>{},policy:{maxBytes:1024,timeoutMs:100,redirects:2,minIntervalMs:0}});}
const source=fixture().source;

test('new official filing discovery retains issuer, accession, period and amendment',()=>{const d=index('MSFT');d.filings.recent.form[0]='10-Q/A';const s=submissions('MSFT',d,{asOf:'2026-11-02'})[0];assert.equal(s.periodEnd,'2026-09-30');assert.equal(s.amendmentStatus,'AMENDED');assert(s.url.includes('/789019/'));});
test('duplicate filing discovery does not duplicate economics',()=>{const d=index('MSFT');for(const [k,v]of Object.entries(d.filings.recent))d.filings.recent[k]=v.concat(v);assert.equal(submissions('MSFT',d,{asOf:'2026-11-02'}).length,1);});
test('future filing discovery excluded by explicit clock',()=>assert.equal(submissions('MSFT',index('MSFT'),{asOf:'2026-10-01'}).length,0));
test('wrong SEC issuer and invalid columns fail closed',()=>{const d=index('MSFT');assert.throws(()=>submissions('GOOG',d,{asOf:'2026-11-02'}),/ISSUER/);d.filings.recent.form=[];assert.throws(()=>submissions('MSFT',d,{asOf:'2026-11-02'}),/COLUMNS/);});
test('known accession excluded from new filing candidates',()=>{const s=submissions('MSFT',index('MSFT'),{asOf:'2026-11-02'})[0];assert.equal(submissions('MSFT',index('MSFT'),{asOf:'2026-11-02',known:[s]}).length,0);});
test('IR discovery accepts official delegation, excludes third-party links',()=>{const html='<p>earnings</p><a href="https://s206.q4cdn.com/479360582/files/2026/q3/earnings.pdf">2026 Q3 earnings</a><a href="https://finance.example.com/2026/earnings">earnings</a>';const d=archiveLinks('GOOG',html,'https://abc.xyz/investor/earnings/');assert.equal(d.length,1);assert.equal(d[0].parser,'pdf');assert.equal(d[0].publicationDate,null);});
for(const status of [403,429])test(status+' stops this host, records Retry-After and makes no retry',async()=>{let calls=0;const f=fetcher(async()=>{calls++;return new Response('blocked',{status,headers:{'retry-after':'120'}})});assert.equal((await f.get(source)).status,'ACCESS_BLOCKED');assert.equal((await f.get(source)).attempted,false);assert.equal(calls,1);assert.equal(f.blocked.get('www.microsoft.com').retryAfter,'120');});
test('timeout fails safely',async()=>{const f=fetcher(async(_,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('timeout')))));assert.equal((await f.get(source)).status,'FAILED_WITH_LAST_VALID');});
test('max size enforced while streaming even with missing Content-Length',async()=>{const f=fetcher(async()=>new Response('x'.repeat(1025)));assert.equal((await f.get(source)).error,'MAX_RESPONSE_SIZE');});
test('size header is checked before buffering',async()=>{const f=fetcher(async()=>new Response('x',{headers:{'content-length':'1000000'}}));assert.equal((await f.get(source)).error,'MAX_RESPONSE_SIZE');});
test('redirect to unrelated host rejected before second request',async()=>{let calls=0;const f=fetcher(async()=>{calls++;return new Response('',{status:302,headers:{location:'https://example.com/payload'}})});assert.equal((await f.get(source)).error,'OFFICIAL_HOST');assert.equal(calls,1);});
test('redirect limit bounded',async()=>{let n=0;const f=fetcher(async()=>{n++;return new Response('',{status:302,headers:{location:source.url}})});assert.equal((await f.get(source)).error,'REDIRECT_LIMIT');assert.equal(n,3);});
test('SEC issuer paths cannot be substituted',()=>assert.throws(()=>permitted('MSFT','https://data.sec.gov/submissions/CIK0001652044.json'),/ISSUER/));
test('delegated CDN requires correct company tenant and issuer parent',()=>{assert.throws(()=>permitted('GOOG','https://s206.q4cdn.com/479360582/a.pdf'),/DELEGATION/);assert.throws(()=>permitted('GOOG','https://s206.q4cdn.com/399680738/a.pdf','https://abc.xyz/investor/'),/TENANT/);assert(permitted('GOOG','https://s206.q4cdn.com/479360582/a.pdf','https://abc.xyz/investor/'));});
test('safe source receipt and immutable cache retain raw identities',async()=>{const f=fetcher(async()=>new Response('fixture',{headers:{'content-type':'text/html'}}));const r=await f.get(source);assert.equal(r.receipt.sha256,sha256('fixture'));assert.equal(r.receipt.byteSize,7);assert.equal(r.receipt.canonicalOfficialHost,'www.microsoft.com');assert.equal(cacheObject(f.cache,r.receipt.sha256,7).toString(),'fixture');fs.writeFileSync(path.join(f.cache,'objects',r.receipt.sha256.slice(0,2),r.receipt.sha256),'wrong');assert.throws(()=>cacheObject(f.cache,r.receipt.sha256),/CORRUPT/);});
test('same URL changed hash, new URL same filing and amendments retained for review',()=>{const accepted=[{...source,accession:'0000789019-26-000099'}];assert.equal(detectSourceChanges(source,{sha256:'f'.repeat(64)},accepted)[0].type,'SAME_URL_CHANGED_BYTES');assert.equal(detectSourceChanges({...source,url:source.url+'-new',accession:accepted[0].accession},{sha256:source.sha256},accepted)[0].type,'NEW_URL_SAME_FILING');assert.equal(detectSourceChanges({...source,amendmentStatus:'AMENDED'},{sha256:source.sha256},[])[0].type,'AMENDED_FILING');});
test('native label binding preserves accepted active definition versions',()=>{const f=fixture();const b=bindDefinitions(f.rows,data.input.observations,data.definitions);assert.equal(b.rows.length,4);assert.equal(b.issues.length,0);validateRows(b.rows,[f.source],data.definitions,'2026-11-02');});
test('changed native metric label never guesses a definition',()=>{const f=fixture();f.rows[0].nativeLabel='AI-adjusted revenue';const b=bindDefinitions(f.rows,data.input.observations,data.definitions);assert.equal(b.rows.length,3);assert.equal(b.issues[0].comparabilityStatus,'REVIEW_REQUIRED');});
for(const [label,mutate] of [['unit',r=>r.unit='USD'],['scope',r=>r.scope='AI_ONLY'],['date',r=>r.periodEnd='2026-09-31'],['quarter-start',r=>r.periodStart='2026-01-01'],['duplicate',(_r,rows)=>rows.push(clone(rows[0]))],['future-release',(_r,_rows,s)=>s.publicationDate='2026-12-01']])test('candidate validation rejects '+label,()=>{const f=fixture();mutate(f.rows[0],f.rows,f.source);assert.throws(()=>validateRows(f.rows,[f.source],data.definitions,'2026-11-02'));});
function duration(){const r=fixture('GOOG').rows.find(r=>r.metric==='cfo');return {long:{...r,observationId:'long',periodStart:'2026-01-01',periodType:'YTD',value:900},short:{...r,observationId:'short',periodStart:'2026-01-01',periodEnd:'2026-06-30',periodType:'YTD',value:500},proof:{reviewed:true,reason:'explicit same recast basis',sourceIds:[r.sourceId],restatementBasis:r.restatementBasis,operandIds:['long','short']}};}
test('Q3 equals 9M minus H1 with proof, exact periods and same scope',()=>{const {long,short,proof}=duration(),r=reconstruct(long,short,proof);assert.equal(r.value,400);assert.equal(r.periodStart,'2026-07-01');assert.deepEqual(r.calculation.operandIds,['long','short']);});
test('Q2 equals H1 minus Q1; Q4 equals FY minus 9M',()=>{const f=duration();f.long.periodEnd='2026-06-30';f.short.periodEnd='2026-03-31';f.short.periodType='Q';assert.equal(reconstruct(f.long,f.short,f.proof).periodStart,'2026-04-01');f.long.periodEnd='2026-12-31';f.long.periodType='FY';f.short.periodEnd='2026-09-30';f.short.periodType='YTD';assert.equal(reconstruct(f.long,f.short,f.proof).periodStart,'2026-10-01');});
for(const key of ['definitionVersion','unit','scope','restatementBasis','periodStart','precision'])test('incompatible YTD rejected: '+key,()=>{const f=duration();f.short[key]='wrong';assert.throws(()=>reconstruct(f.long,f.short,f.proof));});
test('YTD reconstruction never invents missing compatibility proof',()=>{const f=duration();assert.throws(()=>reconstruct(f.long,f.short,null),/VINTAGE/);});
test('standalone quarter preferred, not averaged with YTD',()=>{const f=duration(),r={...f.long,periodStart:'2026-07-01',periodType:'Q',value:333};assert.equal(selectQuarter([f.long,f.short,r],'GOOG','2026-09-30',[f.proof]).selected[0].value,333);});
test('multiple standalone numeric contexts remain review-required',()=>{const r=fixture().rows[0];assert.equal(selectQuarter([r,{...r,observationId:'other',value:999}],'MSFT','2026-09-30').selected.length,0);});
for(const [company,expected]of [['MSFT',300],['GOOG',300],['AMZN',310],['META',250]])test(company+' core FCF scope unchanged, optional missingness independent',()=>{const f=fixture(company),q=qualifyQuarter(company,'2026-09-30',f.rows);assert.equal(q.status,'QUALIFIED_CANDIDATE');assert.equal(q.rows.find(r=>r.metric==='fcfCompanyConvention').value,expected);assert.equal(q.optionalFamilies.depreciation.status,'UNAVAILABLE');assert.equal(q.recognizedAiRevenue.status,'UNAVAILABLE');assert.equal(q.aiReturns.status,'NOT_IDENTIFIED');});
test('reported FCF discrepancy cannot auto-resolve',()=>{const f=fixture();f.rows.push({...f.rows[0],metric:'fcfReported',observationId:'reported',value:299});assert.equal(qualifyQuarter('MSFT','2026-09-30',f.rows).status,'REVIEW_REQUIRED');});
test('restated comparatives preserve old accepted versus new candidate',()=>{const old=clone(data.input.observations[0]),r={...old,value:old.value+1,sourceId:'new'};const changes=detectRestatements([r],[old]);assert.equal(changes[0].oldAccepted.value,old.value);assert.equal(changes[0].newCandidate.value,old.value+1);assert.equal(changes[0].acceptedHistoryModified,false);});
test('definition and segment recast changes receive explicit review',()=>{const old=clone(data.input.observations.find(r=>r.metric==='segmentRevenue')),r={...old,definitionVersion:'NEW_RECAST_V2'};assert.equal(detectRestatements([r],[old])[0].type,'DEFINITION_VERSION_CHANGE');});
test('lease and RPO policy review cannot silently become approved definitions',()=>{const f=fixture(),q=qualifyQuarter('MSFT','2026-09-30',f.rows,{reviewItems:[{type:'LEASE_POLICY',status:'REVIEW_REQUIRED'},{metric:'rpo',type:'RPO_DEFINITION',status:'REVIEW_REQUIRED'}]});assert.equal(q.optionalFamilies.backlog.status,'REVIEW_REQUIRED');assert.equal(q.reviewItems.length,2);});
test('candidate monitor adds qualified records with frozen arithmetic and no promotion',()=>{const q=qualifyQuarter('MSFT','2026-09-30',fixture().rows),m=candidateMonitor(data,[q]);assert.equal(m.content.status,'CANDIDATE_MONITOR');assert.equal(m.content.sharedPublicQuarter,'2026Q2');assert.equal(m.content.proposedHeadlineQuarter,null);assert.equal(m.content.records.find(r=>r.metric==='operatingMargin').value,10);assert.equal(m.content.records.find(r=>r.metric==='fcfMargin').value,30);validateCandidate(m,data,[q]);const bad=clone(m);bad.content.records[0].value=999;assert.throws(()=>validateCandidate(bad,data,[q]),/SEMANTIC/);});
test('all-four quarter only proposes advance; public preview NOT FOR PRODUCTION',()=>{const qs=companies.map(c=>qualifyQuarter(c,'2026-09-30',fixture(c).rows)),m=candidateMonitor(data,qs),p=candidatePreview(data,m);assert.equal(m.content.proposedHeadlineQuarter,'2026Q3');assert.equal(p.content.status,'NOT_FOR_PRODUCTION');assert.equal(p.content.acceptedDataThrough,'2026Q2');assert.equal(m.content.recognizedAiRevenue.status,'UNAVAILABLE');});
test('run-rate context stays RUN_RATE and not quarterly or recognized AI revenue',()=>{const e={company:'MSFT',kind:'DIRECT_AI_RUN_RATE',periodType:'RUN_RATE',value:37000,recognizedRevenue:false,status:'REVIEW_REQUIRED'};const m=candidateMonitor(data,[],{events:[e]});assert.equal(m.content.events[0].value,37000);assert.equal(m.content.events[0].periodType,'RUN_RATE');assert.equal(m.content.recognizedAiRevenue.status,'UNAVAILABLE');});
test('human promotion gate requires exact reviewed hash, all companies, research-only target',()=>{const qs=companies.map(c=>qualifyQuarter(c,'2026-09-30',fixture(c).rows)),m=candidateMonitor(data,qs);assert.throws(()=>promotionGate(null,m),/REVIEW/);const review={reviewed:true,reviewer:'fixture reviewer',approvedAt:'2026-11-02T12:00:00Z',target:'RESEARCH_ONLY',candidateMonitorHash:m.resultHash,approvedCompanies:companies};assert.equal(promotionGate(review,m).productionWritePerformed,false);assert.throws(()=>promotionGate({...review,target:'PRODUCTION'},m));assert.throws(()=>promotionGate({...review,approvedCompanies:['MSFT']},m));});
test('economic hash includes raw source identity but excludes execution timestamps',()=>{const q=qualifyQuarter('MSFT','2026-09-30',fixture().rows);const a=candidateMonitor(data,[q],{sourceIdentities:[{sourceId:'s',sha256:'a'.repeat(64)}]}),b=candidateMonitor(data,[q],{sourceIdentities:[{sourceId:'s',sha256:'b'.repeat(64)}]});assert.notEqual(a.resultHash,b.resultHash);assert.equal(bytes(candidateMonitor(data,[q])),bytes(candidateMonitor(data,[q])));});
test('fresh-process rebuild deterministic bytes and hash',()=>{const code="import {fixture,data} from './research/ai-capex-monetization/refresh/tests/helpers.mjs';import {qualifyQuarter} from './research/ai-capex-monetization/refresh/scripts/qualify.mjs';import {candidateMonitor} from './research/ai-capex-monetization/refresh/scripts/monitor.mjs';import {bytes} from './research/ai-capex-monetization/scripts/contract.mjs';console.log(bytes(candidateMonitor(data,[qualifyQuarter('MSFT','2026-09-30',fixture().rows)])));";const run=()=>{const p=spawnSync(process.execPath,['--input-type=module','-e',code],{encoding:'utf8',maxBuffer:2000000});assert.equal(p.status,0,p.stderr);return p.stdout;};assert.equal(run(),run());});
test('calendar, quarter and explicit timestamp reject invalid normalization',()=>{assert.throws(()=>quarter('2026-09-31'));assert.throws(()=>timestamp('2026-02-30T12:00:00Z'));assert.throws(()=>timestamp('2026-11-02T24:00:00Z'));assert.equal(timestamp('2026-11-02T12:00:00Z'),'2026-11-02T12:00:00Z');});
test('source qualification checks pinned bytes, publication and retrieval clock',()=>{const f=fixture(),cache=temp();f.source.sha256=putObject(cache,Buffer.from('fixture'));qualifySource(f.source,cache,'2026-11-02');assert.throws(()=>qualifySource(f.source,cache,'2026-10-01'),/CLOCK/);});
test('no new data generates receipts only, no fake economic identity or preview',async()=>{const out=temp(),cache=temp();const response=async url=>{const company=companies.find(c=>url.includes({MSFT:'0000789019',GOOG:'0001652044',AMZN:'0001018724',META:'0001326801'}[c]));if(company){const d=index(company);for(const key of Object.keys(d.filings.recent))d.filings.recent[key]=[];return new Response(JSON.stringify(d));}return new Response('<p>earnings archive; no static qualified disclosure links</p>');};const a=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:response}),b=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:response});assert.equal(a.economic,null);assert.equal(b.receipt.economicChange,false);assert.equal(b.receipt.resultHash,null);assert(!fs.existsSync(path.join(out,'current.json')));});
test('one IR host failure isolated from other companies',async()=>{const out=temp(),cache=temp();const response=async url=>url.includes('microsoft.com')?new Response('blocked',{status:403}):url.includes('/submissions/')?new Response('{}'):new Response('<p>earnings archive</p>');const r=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:response});assert.equal(r.receipt.companyResults[0].status,'ACCESS_BLOCKED');assert.equal(r.receipt.companyResults.length,4);assert.equal(r.receipt.companyResults[1].sourceFamilies.IR_ARCHIVE.status,'REVIEW_REQUIRED');});
test('research path guard prevents src/public writes and raw cache in Git',async()=>{await assert.rejects(refresh({asOf:'2026-11-02',clock,cache:process.cwd(),out:temp()}),/EXTERNAL/);await assert.rejects(refresh({asOf:'2026-11-02',clock,out:path.join(process.cwd(),'src')}),/RESEARCH_OUTPUT/);});
test('no email, schedule, runtime LLM or production changes in Phase 2D source',()=>{const source=fs.readdirSync('research/ai-capex-monetization/refresh/scripts').filter(f=>fs.statSync('research/ai-capex-monetization/refresh/scripts/'+f).isFile()).map(f=>fs.readFileSync('research/ai-capex-monetization/refresh/scripts/'+f,'utf8')).join('\n');assert(!/sendMail|SMTP|OPENAI_API_KEY|ANTHROPIC_API_KEY|workflow_dispatch|schedule:|\.github\/workflows/.test(source));assert(!/writeFileSync\([^\n]*['"](?:src|public)\//.test(source));});

test('delegation proof cannot use HTTP or credentials',()=>{assert.throws(()=>permitted('GOOG','https://s206.q4cdn.com/479360582/a.pdf','http://abc.xyz/investor/'));assert.throws(()=>permitted('GOOG','https://s206.q4cdn.com/479360582/a.pdf','https://user:password@abc.xyz/investor/'));});
test('full candidate refresh twice preserves immutable bytes and last-valid identity',async()=>{
 const out=temp(),cache=temp(),before=hash(data);const indexDoc=index('MSFT');
 const response=async url=>{if(url.includes('CIK0000789019'))return new Response(JSON.stringify(indexDoc));if(url.includes('/submissions/')){const c=companies.find(c=>url.includes({GOOG:'0001652044',AMZN:'0001018724',META:'0001326801'}[c]));const d=index(c);for(const k of Object.keys(d.filings.recent))d.filings.recent[k]=[];return new Response(JSON.stringify(d));}if(url.includes('/Archives/'))return new Response('fixture');return new Response('<p>earnings archive</p>');};
 const parser=async source=>{const f=fixture();return {source,observations:f.rows.map(r=>({...r,sourceId:source.sourceId,observationId:source.sourceId+':'+r.metric,restatementBasis:source.sourceId})),events:[],reviewItems:[]};};
 const a=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:response,parser});assert.equal(a.economic.content.qualification[0].status,'QUALIFIED_CANDIDATE');
 const file=path.join(out,'generations',a.economic.resultHash,'candidate-monitor.json'),first=fs.readFileSync(file,'utf8');
 const b=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:response,parser});assert.equal(a.economic.resultHash,b.receipt.resultHash);assert.equal(b.economic,null);assert.equal(fs.readFileSync(file,'utf8'),first);assert.equal(b.receipt.economicChange,false);assert.equal(hash(data),before);
 const c=await refresh({out,cache,asOf:'2026-11-02',clock,fetcher:async()=>new Response('blocked',{status:403}),parser});assert.equal(c.economic,null);assert.equal(c.receipt.resultHash,a.economic.resultHash);assert.equal(fs.readFileSync(file,'utf8'),first);
});

test('Amazon disclosed net cash PP&E must reconcile to gross less proceeds',()=>{const f=fixture('AMZN');f.rows.push({...f.rows.find(r=>r.metric==='cashPpeGross'),metric:'cashPpeNet',observationId:'reported-net',value:199});assert.equal(qualifyQuarter('AMZN','2026-09-30',f.rows).status,'REVIEW_REQUIRED');});
test('optional core-independent definition ambiguity does not invalidate complete core',()=>{const f=fixture();assert.equal(qualifyQuarter('MSFT','2026-09-30',f.rows,{reviewItems:[{metric:'depreciationPpe',type:'METRIC_LABEL_OR_DEFINITION_CHANGE',status:'REVIEW_REQUIRED'}]}).status,'QUALIFIED_CANDIDATE');});
test('amended/changed source identity blocks unattended core qualification',()=>{const f=fixture();for(const type of ['SAME_URL_CHANGED_BYTES','AMENDED_FILING','NEW_URL_SAME_FILING'])assert.equal(qualifyQuarter('MSFT','2026-09-30',f.rows,{reviewItems:[{type,status:'REVIEW_REQUIRED'}]}).status,'REVIEW_REQUIRED');});

test('symlink output/cache paths cannot bypass production isolation',async()=>{const dir=temp(),link=path.join(dir,'production-link');fs.symlinkSync(process.cwd(),link,'dir');await assert.rejects(refresh({asOf:'2026-11-02',clock,cache:link,out:temp()}),/EXTERNAL/);const src=path.join(dir,'src-link');fs.symlinkSync(path.join(process.cwd(),'src'),src,'dir');await assert.rejects(refresh({asOf:'2026-11-02',clock,cache:temp(),out:src}),/RESEARCH_OUTPUT/);});

test('human optional-family review requires exact acknowledged review-item identity',()=>{const qs=companies.map(c=>qualifyQuarter(c,'2026-09-30',fixture(c).rows)),changes=[{type:'MISSING_OPTIONAL_DEPRECIATION',status:'REVIEW_REQUIRED'}],m=candidateMonitor(data,qs,{sourceChanges:changes});const review={reviewed:true,reviewer:'fixture reviewer',approvedAt:'2026-11-02T12:00:00Z',target:'RESEARCH_ONLY',candidateMonitorHash:m.resultHash,approvedCompanies:companies};assert.throws(()=>promotionGate(review,m),/ACKNOWLEDGED/);assert.equal(promotionGate({...review,acknowledgedReviewItemsHash:hash(changes)},m).productionWritePerformed,false);});

test('wrong publisher cannot pass raw source qualification',()=>{const f=fixture(),cache=temp();f.source.sha256=putObject(cache,Buffer.from('fixture'));f.source.publisher='Fabricated Publisher';assert.throws(()=>qualifySource(f.source,cache,'2026-11-02'),/PUBLISHER/);});
test('human review timestamp cannot precede publisher disclosure',()=>{const qs=companies.map(c=>qualifyQuarter(c,'2026-09-30',fixture(c).rows)),m=candidateMonitor(data,qs,{sourceIdentities:[{sourceId:'s',publicationDate:'2026-10-28',sha256:'a'.repeat(64)}]});assert.throws(()=>promotionGate({reviewed:true,reviewer:'fixture',approvedAt:'2026-10-01T12:00:00Z',target:'RESEARCH_ONLY',candidateMonitorHash:m.resultHash,approvedCompanies:companies},m),/BEFORE_DISCLOSURE/);});
