import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { load } from '../scripts/validate-phase3b.mjs';
import { sha256 } from './archive.mjs';
const cache=process.env.WIL_AI_INFRA_CACHE||path.join(os.homedir(),'Public/wil-ai-infrastructure-cache');
const sources=load().sources.filter(s=>s.SHA256);
const results=sources.map(s=>{const file=path.join(cache,'objects',s.SHA256.slice(0,2),s.SHA256);if(!fs.existsSync(file))return{sourceId:s.sourceId,status:'MISSING_OBJECT'};const bytes=fs.readFileSync(file);return{sourceId:s.sourceId,status:sha256(bytes)===s.SHA256&&bytes.length===s.byteSize?'HASH_MATCH':'CONTENT_MISMATCH',byteSize:bytes.length};});
console.log(JSON.stringify({results,valid:results.every(r=>r.status==='HASH_MATCH'),rawBytes:results.reduce((n,r)=>n+(r.byteSize??0),0)},null,2));
if(results.some(r=>r.status!=='HASH_MATCH'))process.exitCode=1;
