import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { validate, normalize, bytes, derive, fiscalQuarter, date } from '../scripts/contract.mjs';
const fixture = JSON.parse(readFileSync(new URL('../fixtures/official-anchors.json', import.meta.url)));
const copy = () => structuredClone(fixture);
const row = (b,company,metric) => b.observations.find(o => o.company === company && o.metric === metric && o.periodEnd === '2026-06-30');
const mutate = (fn, code) => {const b=copy(); fn(b); assert.throws(() => validate(b), code);};
test('reviewed official anchors pass contract', () => assert.equal(validate(fixture), true));
for (const [company,end,expected] of [['MSFT','2026-06-30','FY2026Q4'],['MSFT','2025-09-30','FY2026Q1'],['MSFT','2025-12-31','FY2026Q2'],['MSFT','2026-03-31','FY2026Q3'],['GOOG','2026-06-30','FY2026Q2'],['AMZN','2019-06-30','FY2019Q2'],['META','2026-06-30','FY2026Q2']]) test(`fiscal mapping ${company}/${end}`, () => assert.equal(fiscalQuarter(company,end),expected));
for (const bad of ['2021-02-29','2026-06-31','2026-13-01']) test(`invalid date ${bad}`,()=>assert.throws(()=>date(bad),/DATE/));
test('valid leap day',()=>assert.equal(date('2020-02-29'),'2020-02-29'));
test('MSFT native CapEx remains distinct from cash plus leases',()=>{assert.equal(row(fixture,'MSFT','nativeCapex').value,41000);assert.equal(row(fixture,'MSFT','cashPpeGross').value,35802);assert.equal(row(fixture,'MSFT','financeLeaseAdditions').value,5600);assert.notEqual(41000,35802+5600);});
test('Meta exact native bridge includes principal once',()=>assert.equal(row(fixture,'META','nativeCapex').value,30116+962));
test('Amazon net purchases subtract proceeds',()=>assert.equal(row(fixture,'AMZN','cashPpeNet').value,54208-1132));
for (const [company,source,metric,value] of [['MSFT','ms26','cashFcf',19639],['GOOG','goog26','cashFcf',-5855],['AMZN','amzn26','cashFcf',-7689],['META','meta26','cashFcfIncludingLeasePrincipal',784]]) test(`${company} cash bridge independently expected`,()=>assert.equal(derive(fixture,company,'2026-06-30',source).find(o=>o.metric===metric).value,value));
test('missing stays null, not zero',()=>mutate(b=>row(b,'MSFT','depreciationPpe').value=0,/MISSING/));
test('missing reason required',()=>mutate(b=>delete row(b,'MSFT','depreciationPpe').unavailableReason,/MISSING/));
test('duplicate filing with new ID still rejected',()=>mutate(b=>b.observations.push({...b.observations[0],observationId:'duplicate'}),/DUPLICATE_FILING/));
test('duplicate source identity rejected',()=>mutate(b=>b.sources.push({...b.sources[0]}),/SOURCE_ID/));
test('different disclosed vintage retained, not silently overwritten',()=>{const b=copy();b.sources.push({...b.sources[0],sourceId:'ms26-amended',sourceDate:'2026-08-01'});b.observations.push({...b.observations[0],observationId:'ms26-amended:revenue',sourceId:'ms26-amended',value:90008,revisionStatus:'REVISED'});assert.equal(normalize(b).content.observations.filter(o=>o.company==='MSFT'&&o.metric==='revenue'&&o.periodEnd==='2026-06-30').length,2);assert.notEqual(normalize(b).contentHash,normalize(fixture).contentHash);});
test('GAAP/non-GAAP label mismatch rejected',()=>mutate(b=>row(b,'META','fcfReported').accountingBasis='GAAP',/METRIC_SCOPE/));
test('backlog cannot become quarterly revenue',()=>mutate(b=>{const o=row(b,'GOOG','rpo');o.periodType='Q';o.frequency='QUARTERLY';o.periodStart='2026-04-01';},/BACKLOG/));
test('run rate cannot become recognized revenue',()=>mutate(b=>{const o=row(b,'AMZN','aiRevenueRunRate');o.periodType='Q';o.frequency='QUARTERLY';o.periodStart='2026-04-01';},/RUN_RATE/));
test('investment gain cannot enter monetization domain',()=>mutate(b=>{const o=b.observations[0];o.metric='investmentGain';o.domain='monetization';},/METRIC_SCOPE/));
test('source publisher required',()=>mutate(b=>delete b.sources[0].publisher,/PROVENANCE/));
test('unofficial URL rejected',()=>mutate(b=>b.sources[0].url='https://analyst.example.com/msft',/PROVENANCE/));
test('wrong company source rejected',()=>mutate(b=>b.observations[0].sourceId='meta26',/OBSERVATION_ID/));
test('wrong money units rejected',()=>mutate(b=>b.observations[0].unit='USD_BILLIONS',/UNIT/));
test('fiscal/calendar inconsistency rejected',()=>mutate(b=>b.observations[0].fiscalQuarter='FY2026Q2',/PERIOD/));
test('YTD never relabeled as a quarter',()=>mutate(b=>{const o=b.observations.find(o=>o.periodType==='YTD');o.periodType='Q';o.frequency='QUARTERLY';},/PERIOD_HORIZON/));
test('future observation rejected',()=>mutate(b=>b.sources[0].sourceDate='2026-05-01',/FUTURE_OBSERVATION/));
test('company AI recognized revenue unavailable, not inferred from cloud',()=>assert.equal(row(fixture,'GOOG','aiRevenueRecognized').value,null));
test('mixed D&A never substitutes for unavailable pure depreciation',()=>assert.equal(row(fixture,'AMZN','depreciationPpe').value,null));
test('forged derived value rejected',()=>mutate(b=>row(b,'AMZN','cashPpeNet').value=54208,/DERIVED_LINEAGE/));
test('lease additions cannot replace principal operand',()=>mutate(b=>row(b,'META','nativeCapex').calculation.inputs[1]=row(b,'MSFT','financeLeaseAdditions').observationId,/DERIVED_LINEAGE/));
test('rounding does not qualify an exact derived cash bridge',()=>mutate(b=>row(b,'META','financeLeasePrincipal').precision='ROUNDED',/DERIVED_LINEAGE/));
test('normalization deterministic under source/observation reorder',()=>{const b=copy();b.sources.reverse();b.observations.reverse();assert.equal(bytes(normalize(b)),bytes(normalize(fixture)));});
test('two fresh processes produce identical bytes',()=>{const script=fileURLToPath(new URL('../scripts/normalize.mjs',import.meta.url));assert.equal(execFileSync(process.execPath,[script],{encoding:'utf8'}),execFileSync(process.execPath,[script],{encoding:'utf8'}));});
test('normalization does not modify reviewed evidence',()=>{const before=bytes(fixture);normalize(fixture);assert.equal(bytes(fixture),before);});
test('positive denominator required',()=>{const b=copy();row(b,'MSFT','revenue').value=0;assert.equal(derive(b,'MSFT','2026-06-30','ms26').find(o=>o.metric==='operatingMargin').value,null);});
test('incomplete quarter operands do not use YTD',()=>assert.equal(derive(fixture,'GOOG','2019-06-30','goog19').find(o=>o.metric==='cashFcf').value,null));
test('native frequency cannot become monthly',()=>mutate(b=>b.observations[0].frequency='MONTHLY',/FREQUENCY/));
test('Microsoft annual fiscal boundary enforced',()=>mutate(b=>{const o=b.observations[0];o.periodType='FY';o.frequency='ANNUAL';o.periodEnd='2025-12-31';o.periodStart='2025-01-01';o.fiscalQuarter='FY2026Q2';o.calendarQuarter='2025Q4';},/FISCAL_YEAR_END/));
test('derived formula and operand lineage explicit',()=>{const out=derive(fixture,'AMZN','2026-06-30','amzn26').find(o=>o.metric==='cashFcf');assert.equal(out.formula,'cfo - cashPpeNet');assert.deepEqual(out.inputs,['amzn26:cfo:CONSOLIDATED:Q:2026-06-30','amzn26:cashPpeNet:CONSOLIDATED:Q:2026-06-30']);});
