import React, { useEffect, useState } from 'react'
import { PageIntro } from '../components/PageIntro.jsx'
import { ProductivityChart, ProductivitySource, number } from '../components/ProductivityChart.jsx'
import { productivitySeries as series } from '../data/productivity.js'
import { aiCopy } from '../i18n/productivity.js'
import { aiAssessment, movement, growth, productivityEras, periodLabel } from '../utils/productivity.js'
import { viewParameter } from '../utils/routing.js'
const groups=['productivity','labor','investment','electricity','growth']
const monitorIds=['OPHNFB','ULCNFB','COMPNFB','PNFIC1','CENSUS_DATACENTER','IPN22112CS','CUUR0000SEHF01','REAL_GDP_WORKER']
function Path({steps}){return <ol className="ai-path">{steps.map(step=><li key={step}>{step}</li>)}</ol>}
function Why({t,index}){return <p className="ai-why"><strong>{t.why}</strong><br/>{t.matter[index]}</p>}
function SelectorChart({ids,language}){const [id,setId]=useState(ids[0]),t=aiCopy[language];return <><label className="ai-series-select">{t.series}<select value={id} onChange={e=>setId(e.target.value)}>{ids.map(id=><option key={id} value={id}>{t.names[id]}</option>)}</select></label><ProductivityChart key={id} s={series[id]} language={language}/></>}
export function AiProductivity({language}) {
 const t=aiCopy[language], [laborRange,setLaborRange]=useState('10'), assessment=aiAssessment(series)
 const focus=viewParameter('focus',groups,'productivity')
 useEffect(()=>{if(window.location.hash.includes('focus='))document.getElementById(`ai-${focus}`)?.scrollIntoView({block:'start'})},[focus])
 return <><PageIntro eyebrow={`RESEARCH / ${t.nav}`} title={t.title} description={t.subtitle}/><div className="content-section global-section ia-page ai-page">
 <p className="ai-principle">{t.principle}</p><p>{t.central}</p><nav className="ai-jump" aria-label={t.nav}>{groups.map((g,i)=><a key={g} href={`#/research/ai-productivity?focus=${g}`}>{t.groups[i]}</a>)}</nav>
 <section className="ia-section"><h2>{t.two}</h2><div className="ia-grid two"><article><h3>{t.short}</h3><Path steps={t.shortSteps}/></article><article><h3>{t.long}</h3><Path steps={t.longSteps}/></article></div><p>{t.dominates}</p><Why t={t} index={0}/></section>
 <section className="ia-section"><h2>{t.horizons}</h2><div className="ia-grid three">{t.horizonNames.map((name,i)=><article key={name}><h3>{name}</h3><p>{t.horizonItems[i]}</p></article>)}</div><p>{t.horizonNote}</p></section>
 <section className="ia-section"><h2>{t.monitor}</h2><p>{t.monitorNote}</p><div className="ai-monitor-grid">{monitorIds.map(id=>{const s=series[id],m=movement(s);return <article className="ai-monitor-card" key={id}><h3>{id==='COMPNFB'?t.compensationGrowth:t.names[id]}</h3><strong className="ai-value">{number(m.last?.value)}%</strong><p>{t.yoy} · {t[m.key]}<br/>{m.last&&periodLabel(m.last.date,s.frequency)}</p><ProductivitySource s={s} language={language} compact/></article>})}</div></section>
 <section className="ia-section"><h2>{t.summary}</h2><div className="ia-grid two">{Object.entries(assessment).map(([key,a])=><article key={key}><h3>{t[`${key}Summary`]}</h3><p>{t.messages[a.code]}</p><p>{a.date&&periodLabel(a.date,'quarterly')}</p><ul>{a.evidence.map(e=><li key={e.id}>{t.names[e.id]}: {number(e.value)}% ({language==='zh'?'上季':'prior quarter'}: {number(e.prior)}%)</li>)}</ul></article>)}</div><details><summary>{t.rules}</summary><p>{t.rulesText}</p></details></section>
 <section className="ia-section" id="ai-productivity"><h2>01 / {t.groups[0]}</h2><p>{t.productivityNote}</p><ProductivityChart s={series.OPHNFB} language={language} primary/><Why t={t} index={0}/></section>
 <section className="ia-section" id="ai-labor"><h2>02 / {t.laborTitle}</h2><p className="ai-principle">{t.laborRelation}</p><p>{t.laborNote}</p><label className="ai-series-select">{t.range}<select value={laborRange} onChange={e=>setLaborRange(e.target.value)}>{['5','10','25','all'].map(v=><option key={v} value={v}>{v==='all'?t.full:`${v} ${language==='zh'?'年':'years'}`}</option>)}</select></label><div className="ai-small-multiples">{['COMPNFB','OPHNFB','ULCNFB'].map(id=><ProductivityChart key={id} s={series[id]} language={language} compact fixedMode="yoy" fixedRange={laborRange}/>)}</div><Why t={t} index={1}/></section>
 <section className="ia-section" id="ai-investment"><h2>03 / {t.investmentTitle}</h2><p>{t.investmentNote}</p><SelectorChart ids={['PNFIC1','A679RC1Q027SBEA','B985RC1Q027SBEA','B935RC1Q027SBEA']} language={language}/><h3>{t.semiconductorTitle}</h3><p>{t.semiconductorNote}</p><SelectorChart ids={['IPG3344S','CENSUS_ELECTRONIC']} language={language}/><Why t={t} index={2}/></section>
 <section className="ia-section" id="ai-electricity"><h2>04 / {t.groups[3]}</h2><h3>{t.constructionTitle}</h3><p>{t.constructionNote}</p><Path steps={t.constructionSteps}/><SelectorChart ids={['CENSUS_DATACENTER','CENSUS_NONRES']} language={language}/><h3>{t.electricityTitle}</h3><p>{t.electricityNote}</p><div className="ia-grid two">{['IPN22112CS','CUUR0000SEHF01'].map(id=><ProductivityChart key={id} s={series[id]} language={language}/>)}</div><ProductivityChart s={series.MHHNGSP} language={language}/><Why t={t} index={3}/></section>
 <section className="ia-section" id="ai-growth"><h2>05 / {t.growthTitle}</h2><Path steps={t.growthSteps}/><p>{t.growthNote}</p><p>{t.workerNote}</p><SelectorChart ids={['REAL_GDP_WORKER','GDPC1','CE16OV']} language={language}/><Why t={t} index={4}/><a className="ia-more" href="#/fiscal">{t.fiscal} →</a><h3>{t.tipsTitle}</h3><p>{t.tipsGood}</p><p>{t.tipsPressure}</p><p>{t.tipsNote}</p><a className="ia-more" href="#/monitor?group=monetary">{t.realRates} →</a></section>
 <section className="ia-section"><h2>{t.history}</h2><p>{t.historyNote}</p><p className="ai-source"><a href="https://www.bls.gov/opub/mlr/2021/article/the-us-productivity-slowdown-the-economy-wide-and-industry-level-analysis.htm" target="_blank" rel="noreferrer">{language==='zh'?'BLS：美国生产率放缓的历史分析':'BLS: historical analysis of the U.S. productivity slowdown'} ↗</a></p><div className="ia-grid three">{productivityEras.map((era,i)=>{const points=growth(series.OPHNFB).filter(p=>p.date>=era.from&&(!era.to||p.date<=era.to)&&Number.isFinite(p.value));const mean=points.reduce((n,p)=>n+p.value,0)/points.length;return <article key={era.id}><h3>{t.eras[i]}</h3><strong>{number(mean)}%</strong><p>{language==='zh'?'季度同比增速的算术平均':'Arithmetic mean of quarterly YoY growth'}<br/>{periodLabel(points[0]?.date||'—','quarterly')} – {periodLabel(points.at(-1)?.date||'—','quarterly')} · n = {points.length}</p><a href={series.OPHNFB.sourceUrl}>BLS / FRED · OPHNFB</a></article>})}</div><Why t={t} index={0}/></section>
 <section className="ia-section"><h2>{t.planned}</h2><ul>{t.plannedItems.map(item=><li key={item}>{item}</li>)}</ul><a className="ia-more" href="#/sources?focus=health">{language==='zh'?'数据来源与健康':'Sources & Data Health'} →</a><p>{t.central}</p><a className="ia-more" href="#/purchasing-power">{t.dollar} →</a></section>
 </div></>
}
export function AiProductivityPreview({language}){const t=aiCopy[language];return <section className="ia-section ai-preview"><p className="eyebrow">{t.nav}</p><h2>{t.preview}</h2><p>{t.subtitle}</p><ul>{(language==='zh'?['生产率','单位劳动成本','AI 投资 · 代理指标','电力需求 · 代理指标']:['Productivity','Unit Labor Cost','AI Investment · proxies','Electricity Demand · proxy']).map((item,i)=><li key={item}><a href={`#/research/ai-productivity?focus=${['productivity','labor','investment','electricity'][i]}`}>{item} →</a></li>)}</ul><a className="ia-more" href="#/research/ai-productivity">{t.explore} →</a></section>}
