import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';
import {build,quarters,proposeManifest,validateManifest,validateInputs,subtractDuration,deriveCash,compatibleGrowth,validateGenerated} from '../scripts/panel.mjs';
import {Retriever,officialURL,validateSource,sha256} from '../scripts/retrieve.mjs';
import {companyFactsCandidates} from '../scripts/company-facts.mjs';import {validateEvents,eventTimeline} from '../scripts/events.mjs';import {load,root} from '../scripts/io.mjs';
import {bytes,hash,fiscalQuarter,companies} from '../../scripts/contract.mjs';
const clone=v=>structuredClone(v);const live=load();const actual=build(live.input,live.manifest,live.definitions);
const source={sourceId:'fixture-msft',company:'MSFT',publisher:'Microsoft',documentType:'OFFICIAL_EARNINGS_RELEASE',url:'https://www.microsoft.com/en-us/investor/earnings/fy-2026-q4/press-release-webcast',accession:null,amendmentStatus:'UNKNOWN',publicationDate:'2026-07-29',retrievedAt:'2026-10-07T00:00:00Z',periodEnd:'2026-06-30',sha256:'a'.repeat(64),byteSize:20,mimeType:'text/html',locator:'Synthetic native-quarter fixture; not accepted economic data'};
const o=(metric,value,extras={})=>({observationId:'fixture:'+metric,sourceId:source.sourceId,company:'MSFT',metric,value,scope:'CONSOLIDATED',unit:'USD_MILLIONS',periodType:'Q',periodStart:'2026-04-01',periodEnd:'2026-06-30',precision:'EXACT',evidenceClass:'OBSERVED',definitionVersion:'fixture-'+metric,restatementBasis:'fixture-msft',revisionStatus:'ORIGINAL_RELEASE_VINTAGE',nativeLabel:metric,locator:'fixture row',comparabilityStatus:'COMPARABLE',...extras});
const definitions=rows=>rows.map(r=>({definitionVersion:r.definitionVersion,company:r.company,metrics:[r.metric],scopes:[r.scope],unit:r.unit,effectiveFrom:'2019-01-01',effectiveTo:null,changeReason:'Synthetic contract test'}));
function fixture(){const rows=[o('revenue',100),o('operatingIncome',20),o('cfo',60),o('cashPpeGross',30)];return {schemaVersion:'ai-capex-quarterly-input-v0.1',sources:[clone(source)],observations:rows};}
const f=fixture();const fm=proposeManifest(f);fm.reviewed=true;
test('2019Q1–2026Q2 contains exactly 30 distinct calendar quarters',()=>{assert.equal(quarters().length,30);assert.equal(quarters()[0].periodEnd,'2019-03-31');assert.equal(quarters().at(-1).periodEnd,'2026-06-30');});
test('Microsoft fiscal year mapping remains native',()=>{assert.equal(fiscalQuarter('MSFT','2026-06-30'),'FY2026Q4');assert.equal(fiscalQuarter('MSFT','2025-09-30'),'FY2026Q1');assert.equal(fiscalQuarter('META','2026-06-30'),'FY2026Q2');});
for(const url of ['http://www.microsoft.com/x','https://evil.example/x','https://www.microsoft.com.evil.example/x','https://user:secret@www.microsoft.com/x','https://www.microsoft.com:444/x'])test('reject unofficial endpoint '+new URL(url).host,()=>assert.throws(()=>officialURL('MSFT',url)));
test('CDN delegation and tenant are mandatory',()=>{assert.throws(()=>officialURL('AMZN','https://s2.q4cdn.com/299287126/x.pdf'));assert.throws(()=>officialURL('AMZN','https://s2.q4cdn.com/399680738/x.pdf','https://ir.aboutamazon.com/'));assert.equal(officialURL('AMZN','https://s2.q4cdn.com/299287126/x.pdf','https://ir.aboutamazon.com/'),'https://s2.q4cdn.com/299287126/x.pdf');});
test('SEC URL binds issuer and accession',()=>{const s={...source,url:'https://www.sec.gov/Archives/edgar/data/789019/000078901926000001/x.htm',accession:'0000789019-26-000001'};assert.equal(validateSource(s),true);assert.throws(()=>validateSource({...s,company:'GOOG',publisher:'Alphabet'}),/SEC_URL_IDENTITY/);assert.throws(()=>validateSource({...s,accession:'0000789019-26-000002'}),/SEC_ACCESSION_IDENTITY/);});
const facts={cik:789019,entityName:'Microsoft',facts:{'us-gaap':{Revenue:{label:'Revenue',description:'Whole entity revenue',units:{USD:[{start:'2026-04-01',end:'2026-06-30',filed:'2026-07-30',accn:'0000789019-26-000001',form:'10-Q',val:100000000,fy:2026,fp:'Q4'}]}}}}};
test('SEC Company Facts is candidate-only, USD preserved without synthetic quarters',()=>{const r=companyFactsCandidates(facts,'MSFT',{revenue:'Revenue'})[0];assert.equal(r.value,100000000);assert.equal(r.unit,'USD');assert.equal(r.acceptanceStatus,'CANDIDATE_REQUIRES_NATIVE_SCOPE_REVIEW');assert.equal(r.accession,'0000789019-26-000001');});
test('SEC wrong issuer, units and duplicate context fail closed',()=>{assert.throws(()=>companyFactsCandidates(facts,'GOOG',{}),/ISSUER/);const bad=clone(facts);bad.facts['us-gaap'].Revenue.units={EUR:[]};assert.throws(()=>companyFactsCandidates(bad,'MSFT',{revenue:'Revenue'}),/UNIT/);const duplicate=clone(facts);duplicate.facts['us-gaap'].Revenue.units.USD.push(clone(duplicate.facts['us-gaap'].Revenue.units.USD[0]));assert.throws(()=>companyFactsCandidates(duplicate,'MSFT',{revenue:'Revenue'}),/DUPLICATE/);});
const badFields=[['unit','USD'],['periodStart','2026-01-01'],['periodEnd','2026-06-31'],['scope','AI_BUSINESS'],['precision','UNKNOWN'],['value',null],['evidenceClass','RUN_RATE'],['definitionVersion','invented'],['restatementBasis',null],['locator',null],['metric','aiRevenueRunRate']];
for(const [key,value]of badFields)test('input semantic guard '+key,()=>{const bad=clone(f);bad.observations[0][key]=value;assert.throws(()=>validateInputs(bad,definitions(f.observations)));});
test('duplicate observation ID and economic context reject',()=>{const bad=clone(f);bad.observations.push(clone(bad.observations[0]));assert.throws(()=>validateInputs(bad,definitions(f.observations)),/OBSERVATION_ID/);bad.observations.at(-1).observationId='different';assert.throws(()=>validateInputs(bad,definitions(f.observations)),/DUPLICATE_CONTEXT/);});
test('definition effective period and registered unit are enforced',()=>{const d=definitions(f.observations);d[0].effectiveFrom='2026-07-01';assert.throws(()=>validateInputs(f,d),/EFFECTIVE/);d[0].effectiveFrom='2019-01-01';d[0].unit='USD';assert.throws(()=>validateInputs(f,d),/PROVENANCE/);});
for(const [end,shortEnd,longVal,shortVal,type,expected]of [['2026-06-30','2026-03-31',70,30,'YTD',40],['2026-09-30','2026-06-30',120,70,'YTD',50],['2025-12-31','2025-09-30',200,120,'FY',80]])test('duration subtraction '+end,()=>{const year=end.slice(0,4),a=o('cfo',longVal,{company:'META',periodStart:year+'-01-01',periodEnd:end,periodType:type}),b={...a,observationId:'short',value:shortVal,periodEnd:shortEnd,periodType:'YTD'};if(end==='2026-09-30'){// outside frozen panel target is deliberately unavailable
 assert.throws(()=>subtractDuration(a,b,{reviewed:true,reason:'same note',sourceIds:[a.sourceId],restatementBasis:a.restatementBasis}),/BOUNDARY/);return;}
 const r=subtractDuration(a,b,{reviewed:true,reason:'Same filing note and accounting definition',sourceIds:[a.sourceId],restatementBasis:a.restatementBasis});assert.equal(r.value,expected);assert.equal(r.evidenceClass,'CALCULATED_FROM_DISCLOSED_VALUES');assert.deepEqual(r.calculation.operandIds,[a.observationId,b.observationId]);});
test('Q3 subtraction uses supported target-year boundaries',()=>{const a=o('cfo',120,{company:'META',periodStart:'2025-01-01',periodEnd:'2025-09-30',periodType:'YTD'}),b={...a,observationId:'h1',periodEnd:'2025-06-30',value:70};const r=subtractDuration(a,b,{reviewed:true,reason:'same basis',sourceIds:[a.sourceId],restatementBasis:a.restatementBasis});assert.equal(r.value,50);assert.equal(r.periodStart,'2025-07-01');});
test('duration subtraction rejects missing proof, wrong vintage, scope or noncontiguous boundaries',()=>{const a=o('cfo',100,{company:'META',periodType:'YTD',periodStart:'2026-01-01'}),b={...a,observationId:'q1',value:60,periodEnd:'2026-03-31',periodType:'Q'};const proof={reviewed:true,reason:'native',sourceIds:[a.sourceId],restatementBasis:a.restatementBasis};assert.throws(()=>subtractDuration(a,b,null));for(const change of [{restatementBasis:'old'},{scope:'OTHER'},{definitionVersion:'old'},{periodEnd:'2026-02-28'},{precision:'ROUNDED'}])assert.throws(()=>subtractDuration(a,{...b,...change},proof));});
test('Microsoft fiscal YTD cannot start in January',()=>{const a=o('cfo',100,{periodType:'FY',periodStart:'2026-01-01'}),b={...a,observationId:'9m',periodType:'YTD',value:60,periodEnd:'2026-03-31'};assert.throws(()=>subtractDuration(a,b,{reviewed:true,reason:'native',sourceIds:[a.sourceId],restatementBasis:a.restatementBasis}),/FISCAL/);});
test('manifest proposal is deterministic but requires explicit acceptance',()=>{const shuffled={...f,observations:[...f.observations].reverse()};assert.equal(bytes(proposeManifest(f)),bytes(proposeManifest(shuffled)));assert.throws(()=>validateManifest(f,proposeManifest(f)),/POLICY/);assert.equal(validateManifest(f,fm),true);});
for(const field of ['scope','observationId','definitionVersion','periodEnd'])test('selection identity cannot be forged '+field,()=>{const bad=clone(fm),s=bad.selections.find(s=>s.observationId);s[field]='forged';assert.throws(()=>validateManifest(f,bad));});
test('selection must cover the full matrix, duplicate/missing entry cannot hide a gap',()=>{assert.throws(()=>validateManifest(f,{...fm,selections:fm.selections.slice(1)}),/INCOMPLETE/);assert.throws(()=>validateManifest(f,{...fm,selections:[...fm.selections,fm.selections[0]]}),/DUPLICATE/);});
test('original and comparative vintages retained; latest reviewed vintage selected, not desired trend',()=>{const newer={...source,sourceId:'fixture-newer',publicationDate:'2026-08-01'},old=o('revenue',100),revision={...old,observationId:'comparative',sourceId:newer.sourceId,value:95,revisionStatus:'RESTATED',restatementBasis:newer.sourceId};const input={...f,sources:[source,newer],observations:[old,revision]};const m=proposeManifest(input);assert.equal(m.selections.find(s=>s.metric==='revenue'&&s.company==='MSFT'&&s.periodEnd==='2026-06-30').observationId,'comparative');assert.equal(input.observations[0].value,100);});
const synthetic=(company,entries)=>entries.map(([m,v,extras={}])=>o(m,v,{company,...extras}));
test('Amazon FCF uses net PP&E, lease principal and operating lease cash not deducted again',()=>{const rs=synthetic('AMZN',[['cfo',45387],['cashPpeGross',54208],['ppeProceedsIncentives',1132],['financeLeasePrincipal',395],['operatingLeaseCash',3489]]),d=deriveCash('AMZN',rs);assert.equal(d.find(r=>r.metric==='cashPpeNet').value,53076);const r=d.find(r=>r.metric==='fcfCompanyConvention');assert.equal(r.value,-7689);assert.ok(r.calculation.operandIds.every(Boolean));assert.equal(r.calculation.operandIds.length,2);});
test('Meta uses native net proceeds convention and includes principal exactly once',()=>{const d=deriveCash('META',synthetic('META',[['cfo',12197],['cashPpeGross',7572],['cashPpeNet',7528],['financeLeasePrincipal',219]]));assert.equal(d.find(r=>r.metric==='fcfCompanyConvention').value,4450);assert.equal(d.find(r=>r.metric==='nativeCapex').value,7747);assert.equal(d.find(r=>r.metric==='fcfCompanyConvention').definitionVersion,'META_FCF_NET_CASH_V1');});
test('Meta can use compatible gross vintage without mixing an older net observation',()=>{const d=deriveCash('META',synthetic('META',[['cfo',24724],['cashPpeGross',8258],['cashPpeNet',8258,{restatementBasis:'older'}],['financeLeasePrincipal',944]]));assert.equal(d.find(r=>r.metric==='fcfCompanyConvention').value,15522);assert.equal(d.find(r=>r.metric==='fcfCompanyConvention').definitionVersion,'META_FCF_GROSS_CASH_V2');});
test('missing Meta principal or incompatible vintage stays unavailable',()=>{assert.equal(deriveCash('META',synthetic('META',[['cfo',60],['cashPpeGross',30]])).some(r=>r.metric==='fcfCompanyConvention'),false);assert.equal(deriveCash('MSFT',[o('cfo',60),o('cashPpeGross',30,{restatementBasis:'old'})]).some(r=>r.metric==='fcfCompanyConvention'),false);});
test('cash PP&E is not replaced by asset additions or lease additions',()=>{const d=deriveCash('AMZN',synthetic('AMZN',[['cfo',60],['ppeAdditions',30],['financeLeaseAdditions',10],['ppeProceedsIncentives',2]]));assert.equal(d.some(r=>r.metric==='fcfCompanyConvention'),false);});
test('pure depreciation is not substituted from mixed D&A',()=>{assert.equal(actual.content.completeness.find(r=>r.company==='MSFT'&&r.metric==='depreciationPpe').availableQuarters,0);assert.equal(actual.content.completeness.find(r=>r.company==='MSFT'&&r.metric==='depreciationAmortizationOther').availableQuarters,30);});
test('Microsoft native CapEx does not force a lease reconciliation',()=>{const r=actual.content.reconciliation.find(r=>r.company==='MSFT'&&r.calendarQuarter==='2026Q2');assert.equal(r.capexStatus,'UNRECONCILED_NATIVE_CAPEX_SCOPE');const rs=actual.content.rows.filter(r=>r.company==='MSFT'&&r.calendarQuarter==='2026Q2');assert.equal(rs.find(r=>r.metric==='nativeCapex').value,41000);assert.equal(rs.find(r=>r.metric==='cashPpeGross').value,35802);assert.notEqual(41000,35802+5600);});
test('recognized AI quarterly revenue remains unavailable for all 120 company-quarters',()=>{const rs=actual.content.rows.filter(r=>r.metric==='aiRevenueRecognized');assert.equal(rs.length,120);assert.ok(rs.every(r=>r.value===null));});
test('no synthetic zeros for missing monetization events',()=>{const t=eventTimeline(live.events,quarters(),companies,live.input.sources);assert.equal(t.disclosureCoverage.find(r=>r.company==='META'&&r.calendarQuarter==='2019Q1').status,'NO_DISCLOSURE');assert.equal(t.events.filter(e=>e.kind==='DIRECT_AI_RUN_RATE').length,2);assert.ok(t.events.filter(e=>e.kind==='DIRECT_AI_RUN_RATE').every(e=>e.recognizedRevenue===false));});
test('AI run-rate cannot be converted into quarterly revenue or added to cloud',()=>{const bad=clone(live.events),e=bad.events.find(e=>e.kind==='DIRECT_AI_RUN_RATE');e.periodType='Q';e.value/=4;assert.throws(()=>validateEvents(bad,live.input.sources),/RUN_RATE/);assert.equal(actual.content.rows.filter(r=>r.metric==='segmentRevenue'&&r.value!==null).length,90);});
test('backlog stock and capacity context cannot become flow or numeric score',()=>{const bad=clone(live.events);bad.events.find(e=>e.kind==='BACKLOG').periodType='Q';assert.throws(()=>validateEvents(bad),/BACKLOG/);const b=clone(live.events);b.events.find(e=>e.kind==='CAPACITY_CONSTRAINT').numericScore=1;assert.throws(()=>validateEvents(b),/SCORE/);});
test('material event source hash is bound to pinned manifest',()=>{const bad=clone(live.events);bad.events.find(e=>e.evidenceLevel==='RAW_HASH_QUALIFIED').source.sha256='b'.repeat(64);assert.throws(()=>validateEvents(bad,live.input.sources),/PINNED/);});
test('growth rejects definition break including Alphabet RPO and Microsoft scope',()=>{const a=o('rpo',100,{periodEnd:'2026-06-30',definitionVersion:'RPO_V2'}),b={...a,periodEnd:'2025-06-30',definitionVersion:'RPO_V1',value:80};assert.throws(()=>compatibleGrowth(a,b),/COMPARABLE/);});
test('growth requires exact prior year and positive denominator',()=>{const a=o('cashPpeGross',100),b={...a,observationId:'prior',value:80,periodEnd:'2025-06-30'};assert.equal(compatibleGrowth(a,b).value,25);assert.throws(()=>compatibleGrowth(a,{...b,periodEnd:'2025-03-31'}),/EXACT/);assert.throws(()=>compatibleGrowth(a,{...b,value:0}),/COMPARABLE/);});
test('core gates do not hide Alphabet gap, optional unqualified fields remain independent',()=>{const missing=clone(live.manifest),entry=missing.selections.find(s=>s.company==='GOOG'&&s.metric==='revenue'&&s.periodEnd==='2019-03-31');Object.assign(entry,{observationId:null,scope:null,definitionVersion:null,reason:'Synthetic missing core disclosure'});assert.equal(build(live.input,missing,live.definitions).content.qualification.find(r=>r.company==='GOOG').status,'PARTIAL');assert.equal(actual.content.qualification.find(r=>r.company==='META').status,'CORE_PANEL_QUALIFIED');assert.equal(actual.content.completeness.find(r=>r.company==='META'&&r.metric==='aiRevenueRecognized').status,'UNQUALIFIED');});
test('all 30 directly reported Meta FCF quarters reconcile exactly',()=>{const r=actual.content.reconciliation.filter(r=>r.company==='META'&&r.fcfStatus==='REPORTED_AND_CALCULATED_MATCH');assert.equal(r.length,30);assert.equal(actual.content.reconciliation.filter(r=>r.fcfStatus==='RECONCILIATION_REVIEW_REQUIRED').length,0);});
test('snapshot sorting and runtime retrieval time do not change economic hash',()=>{const b=clone(live.input);b.observations.reverse();b.sources.reverse();b.sources.forEach(s=>s.retrievedAt='2030-01-01T00:00:00Z');assert.equal(bytes(build(b,live.manifest,live.definitions)),bytes(actual));});
test('raw artifact hash changes provenance identity even when arithmetic is unchanged',()=>{const b=clone(live.input);b.sources[0].sha256='b'.repeat(64);const m=clone(live.manifest);m.review.sourceSetHash=hash(b.sources.map(s=>[s.sourceId,s.sha256]).sort((a,b)=>a[0].localeCompare(b[0])));const r=build(b,m,live.definitions);assert.notEqual(r.resultHash,actual.resultHash);assert.equal(bytes(r.content.rows),bytes(actual.content.rows));});
test('generated artifact rejects a self-consistent false value against pinned inputs',()=>{const bad=clone(actual);bad.content.rows.find(r=>r.value!==null).value+=1;bad.resultHash=hash(bad.content);assert.throws(()=>validateGenerated(bad,live.input,live.manifest,live.definitions),/PROVENANCE/);});
test('blocked endpoint suppresses further host requests, other official company still works',async()=>{let count=0;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wil-retriever-'));const r=new Retriever({cache:dir,userAgent:'Research contact: example',sleep:async()=>{},fetcher:async()=>{count++;return count===1?new Response('blocked',{status:403}):new Response('ok',{status:200,headers:{'content-type':'text/html'}});}});try{assert.equal((await r.get(source)).status,'ACCESS_BLOCKED');assert.equal((await r.get({...source,url:'https://www.microsoft.com/other'})).attempted,false);assert.equal((await r.get({...source,sourceId:'fixture-other',company:'GOOG',url:'https://abc.xyz/'})).status,'RETRIEVED');assert.equal(count,2);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('raw cache reuse verifies bytes and corrupt cache fails closed',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wil-cache-'));let calls=0;const r=new Retriever({cache:dir,userAgent:'Research contact: example',sleep:async()=>{},fetcher:async()=>{calls++;return new Response('test bytes',{status:200});}});try{const a=await r.get(source);assert.equal((await r.get(source,{expectedHash:a.sha256})).status,'CACHE_VALIDATED');assert.equal(calls,1);fs.writeFileSync(path.join(dir,'objects',a.sha256.slice(0,2),a.sha256),'bad');await assert.rejects(r.get(source,{expectedHash:a.sha256}),/CORRUPT/);await assert.rejects(r.get(source,{expectedHash:'../unsafe'}),/EXPECTED_HASH/);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('network source failure is isolated and has no access to accepted input mutations',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wil-fail-'));const r=new Retriever({cache:dir,userAgent:'Research contact: example',sleep:async()=>{},fetcher:async()=>{throw Error('network');}});try{const before=bytes(live.input);assert.equal((await r.get(source)).status,'FAILED_WITH_LAST_VALID');assert.equal(bytes(live.input),before);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('official redirect cannot escape allowed source hosts',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wil-redir-'));const r=new Retriever({cache:dir,userAgent:'Research contact: example',sleep:async()=>{},fetcher:async()=>new Response(null,{status:302,headers:{location:'https://evil.example/raw'}})});try{assert.equal((await r.get(source)).status,'FAILED_WITH_LAST_VALID');}finally{fs.rmSync(dir,{recursive:true,force:true});}});
test('two fresh processes produce identical panel bytes and hash',()=>{const script=path.join(root,'scripts/run.mjs'),output=path.join(root,'outputs/panel.json');for(let i=0;i<2;i++){const r=spawnSync(process.execPath,[script],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);const b=fs.readFileSync(output);if(i===0){globalThis.firstPanel=b;}else assert.deepEqual(b,globalThis.firstPanel);}assert.equal(JSON.parse(globalThis.firstPanel).resultHash,actual.resultHash);});

test('accepted selection receipt rejects a changed raw identity without renewed review',()=>{const b=clone(live.input);b.sources[0].sha256='b'.repeat(64);assert.throws(()=>build(b,live.manifest,live.definitions),/SOURCE_SET_IDENTITY/);});

test('derived available rows never retain an UNAVAILABLE placeholder reason',()=>{assert.ok(actual.content.rows.filter(r=>r.availability==='AVAILABLE').every(r=>r.reason===undefined));});

test('native depreciation carries effective-quarter policy flags without moving them backward',()=>{const rs=actual.content.rows.filter(r=>r.company==='AMZN'&&r.metric==='depreciationAmortizationOther');assert.equal(rs.find(r=>r.calendarQuarter==='2024Q1').policyEventsInQuarter.length,1);assert.equal(rs.find(r=>r.calendarQuarter==='2023Q3').policyEventsInQuarter.length,0);assert.ok(actual.content.rows.filter(r=>r.company==='MSFT'&&r.metric==='depreciationAmortizationOther'&&r.value!==null).every(r=>r.policyEventsInQuarter.length===(r.calendarQuarter==='2022Q3'?1:0)));});

test('guidance ranges cannot silently become midpoint observations',()=>{const e=clone(live.events);e.events.find(e=>e.rangeLower!==undefined).value=137500;assert.throws(()=>validateEvents(e,live.input.sources),/RANGE_NOT_POINT/);});
