import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {load as phase3bLoad,canonical} from '../../scripts/validate-phase3b.mjs';
import {schemaErrors} from '../../scripts/validate.mjs';
export const root=fileURLToPath(new URL('../',import.meta.url));
export const VERSION='ai-infrastructure-panel-v0.1.0';
export const COMPANIES=['MSFT','GOOG','AMZN','META','ORCL'];
export const LAYERS=['PHYSICAL_ASSET','ACCOUNTING_EXPOSURE','FINANCING_EXPOSURE','ECONOMIC_OBLIGATION','POWER_INFRASTRUCTURE','MONETIZATION_EVIDENCE'];
export const STATES=['ANNOUNCED','PLANNED','PERMITTED','UNDER_CONSTRUCTION','PARTIALLY_OPERATIONAL','OPERATIONAL','DELAYED','CANCELLED','UNKNOWN'];
export const hash=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(canonical(v))).digest('hex');
const read=f=>JSON.parse(fs.readFileSync(path.join(root,f),'utf8'));
const day=s=>s?.slice(0,10)??null;
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
const map=rows=>new Map(rows.map(r=>[r.id??r.claimId??r.sourceId??r.scopeId??r.observationId,r]));
function layerFor(c,b){
  for(const [group,layer] of [['accounting-bridges','ACCOUNTING_EXPOSURE'],['obligations','ECONOMIC_OBLIGATION'],['power','POWER_INFRASTRUCTURE'],['financing','FINANCING_EXPOSURE'],['ownership','FINANCING_EXPOSURE']])
    if(b[group].some(r=>Object.values(r.fieldClaims).includes(c.claimId)))return layer;
  if(/AI-revenue|attributable|cash-flow|utilization/i.test(c.field))return 'MONETIZATION_EVIDENCE';
  if(/lease|guarantee|PPA/.test(c.field))return 'ECONOMIC_OBLIGATION';
  if(/debt|coupon|maturity|funding/.test(c.field))return 'FINANCING_EXPOSURE';
  if(/PP&E|treatment|equity-20|maximum-exposure/.test(c.field))return 'ACCOUNTING_EXPOSURE';
  return 'PHYSICAL_ASSET';
}
const familyFor=(c,layer)=>['status','project-status'].includes(c.field)?'status':/location|asset-type|site-area|building-area/.test(c.field)?'physical':/legal-title|legal-owner|registered-title|owner$/.test(c.field)?'legalOwner':c.capacityDefinition?'capacity':layer==='MONETIZATION_EVIDENCE'?'monetization':layer==='POWER_INFRASTRUCTURE'?'power':layer==='ACCOUNTING_EXPOSURE'?'accounting':layer==='FINANCING_EXPOSURE'?'financing':layer==='ECONOMIC_OBLIGATION'?'obligations':'physical';
export function loadInput(){
  const b=phase3bLoad(), extra=Object.fromEntries(['projects','entities','claims','relationships','financing','obligations','power','sources','screening'].map(n=>[n,read('input/'+n+'.json')]));
  const sourceRows=b.sources.map(s=>({sourceId:s.sourceId,url:s.url,resolvedURL:s.resolvedURL,publisher:s.publisher,title:s.title,sourceType:s.sourceType,primaryOrSecondary:s.primaryOrSecondary,documentDate:s.documentDate,modifiedAt:null,availableFrom:s.documentDate??day(s.retrievedAt),availabilityBasis:s.documentDate?'DATED_DISCLOSURE_RECONSTRUCTION_NOT_REAL_TIME_VINTAGE':'FIRST_REVIEWED_UNDATED_CONTENT',retrievedAt:s.retrievedAt,MIME:s.MIME,byteSize:s.byteSize,sourceHash:s.SHA256,sourceVersion:s.sourceVersionId??s.sourceId+'@WEB_REVIEW_20261007',qualificationStatus:s.qualificationStatus,retrievalStatus:s.retrievalStatus,accessError:s.accessError,reviewMethod:s.reviewMethod,allowedRoutes:s.allowedRoutes}));
  const projects=b.projects.map(p=>({id:p.id,projectName:p.id==='fairwater'?'Microsoft Fairwater1':p.id==='hyperion'?'Meta Hyperion':'Applied Digital PolarisForge1 / CoreWeave',companyIds:p.id==='hyperion'?['META']:p.id==='fairwater'?['MSFT']:[],assetIdentity:p.assetIdentity,primaryArchetype:p.primaryArchetype,secondaryFeatures:p.secondaryFeatures,candidateState:'QUALIFICATION_CANDIDATE',locationClaimId:p.fieldClaims.location,statusClaimIds:[p.fieldClaims.status],materialClaimIds:Object.values(p.fieldClaims).filter(id=>!id.endsWith(':location')&&!id.endsWith(':status')),relationshipClaimIds:b.relationships.filter(r=>b.claims.find(c=>c.claimId===r.claimId)?.caseId===p.id).map(r=>r.claimId),admissionSourceIds:[...new Set(Object.values(p.fieldClaims).flatMap(id=>b.claims.find(c=>c.claimId===id)?.sourceIds??[]))],announcedAt:null,expectedOperationalDate:null,actualOperationalDate:null,coverageRole:p.id==='polaris-forge-1'?'COMPARATIVE_REFERENCE_CASE':'CORE_COMPANY_PROJECT'}));
  for(const c of extra.claims.filter(c=>c.field==='project-status'&&projects.some(p=>p.id===c.caseId)))projects.find(p=>p.id===c.caseId).statusClaimIds.push(c.claimId);
  const legacyClaims=b.claims.map(c=>({...c,panelLayer:layerFor(c,b),recordState:'CURRENT',condition:null}));
  const scopes=b.scopes.map(s=>({...s,comparisonGroup:null,scopeType:/power|grid/.test(s.scopeId)?'UTILITY_SYSTEM':/platform/.test(s.scopeId)?'CORPORATE_PROGRAM':'PROJECT_NATIVE_SCOPE'}));
  const existing=new Set(scopes.map(s=>s.scopeId));for(const c of extra.claims)if(!existing.has(c.scopeId)){scopes.push({scopeId:c.scopeId,caseId:c.caseId,definition:'Distinct named site; no allocation of company-wide financial values',entityId:c.entityId,period:null,sourceIds:c.sourceIds,comparableTo:[],notComparableTo:[],notes:'No cross-layer addition',comparisonGroup:null,scopeType:'PROJECT_NATIVE_SCOPE'});existing.add(c.scopeId);}
  const entities=[...b.entities,...extra.entities];for(const p of [...projects,...extra.projects])entities.push({id:'unknown:'+p.id,name:'Unidentified reporting/contract entity for '+p.id,entityType:'UNKNOWN',legalName:null,identityStatus:'UNAVAILABLE_PLACEHOLDER_NOT_LEGAL_ENTITY',claimIds:[]});
  const relations=b.relationships.map(r=>({id:r.id,projectId:b.claims.find(c=>c.claimId===r.claimId).caseId,fromId:r.fromId,toId:r.toId,relationshipType:r.relationshipType,claimId:r.claimId,relationshipState:'REPORTED',condition:null}));
  const migrate=(rows,key)=>rows.map(r=>({id:r.id,projectId:r.caseId,[key]:r.instrumentIdentity??r.id,claimIds:[...new Set(Object.values(r.fieldClaims))],issuerId:r.issuerId??null,providerIds:[],obligorId:r.obligorId??null,beneficiaryId:r.beneficiaryId??null,instrumentType:r.obligationType??'SOURCE_NATIVE_INSTRUMENT',maturity:null,coupon:null,security:null,recourse:null,fundingDate:null,status:'REFER_TO_QUALIFIED_FIELD_CLAIMS'}));
  for(const source of [...sourceRows,...extra.sources]){source.sourceFamilyId=source.sourceId;source.previousSourceVersion=null;}
  return {methodology:{implementationVersion:VERSION,implementationHash:hash(['scripts/panel.mjs',...fs.readdirSync(path.join(root,'schemas')).sort().map(n=>'schemas/'+n)].map(f=>[f,fs.readFileSync(path.join(root,f),'utf8')])),baseSha:'940be50f61a1516482da936a38f10a62cf262b5a',companyUniverse:COMPANIES,layers:LAYERS,aggregationPolicy:'DO_NOT_ADD',clockPolicy:'EXPLICIT_AS_OF',publicationPolicy:'FIELD_LEVEL_ONLY_NO_EXPORT',snapshotType:'RECONSTRUCTED_DISCLOSURE_SNAPSHOT_NOT_PUBLISHER_VINTAGE_REPLAY'},projects:[...projects,...extra.projects],entities,claims:[...legacyClaims,...extra.claims],sources:[...sourceRows,...extra.sources],scopes,relationships:[...relations,...extra.relationships],financing:[...migrate(b.financing,'instrumentIdentity'),...extra.financing],obligations:[...migrate(b.obligations,'obligationIdentity'),...extra.obligations],power:[...b.power.map(p=>({id:p.id,projectId:p.caseId,claimIds:Object.values(p.fieldClaims),utilityId:p.utilityId,status:'REFER_TO_QUALIFIED_FIELD_CLAIMS'})),...extra.power],screening:extra.screening,conflicts:b.conflicts,legacyOverlaps:b.overlaps,comparabilityRules:read('input/comparability-rules.json'),publicationRules:read('input/publication-rules.json')};
}
export function inputErrors(b){
  const errors=[],fail=(id,m)=>errors.push(`${id}: ${m}`);
  for(const name of ['projects','entities','claims','sources','scopes','relationships','financing','obligations','power'])errors.push(...schemaErrors(b[name],read('schemas/'+name+'.schema.json'),name));
  if(errors.length)return errors;
  const maps=Object.fromEntries(['projects','entities','claims','sources','scopes','relationships','financing','obligations','power'].map(n=>[n,map(b[n])]));
  for(const n of Object.keys(maps))if(maps[n].size!==b[n].length)fail(n,'duplicate stable ID');
  const ref=(id,n,owner,nullable=false)=>{if(!(nullable&&id===null)&&!maps[n].has(id))fail(owner,`unknown ${n} reference ${id}`);};
  if(new Set(b.projects.map(p=>p.assetIdentity)).size!==b.projects.length)fail('projects','duplicate physical asset');
  const legal= b.entities.filter(e=>e.legalName!==null).map(e=>e.legalName.toLowerCase().replace(/[^a-z0-9]/g,''));
  if(new Set(legal).size!==legal.length)fail('entities','duplicate normalized legal entity');
  const versions=new Set(b.sources.map(s=>s.sourceVersion));for(const s of b.sources){if(s.previousSourceVersion&&!versions.has(s.previousSourceVersion))fail(s.sourceId,'previous source vintage missing');if(!validDate(s.availableFrom)||s.documentDate!==null&&!validDate(s.documentDate))fail(s.sourceId,'invalid source clock');if(s.documentDate&&s.documentDate>s.availableFrom)fail(s.sourceId,'source publication after availability');if(s.sourceHash!==null&&!/^[a-f0-9]{64}$/.test(s.sourceHash))fail(s.sourceId,'invalid source hash');if(s.sourceHash&&s.sourceVersion!==s.sourceId+'@'+s.sourceHash)fail(s.sourceId,'source vintage identity mismatch');if(s.qualificationStatus==='ARCHIVED_REVIEWED'&&(!s.sourceHash||s.byteSize<=0))fail(s.sourceId,'archive identity missing');if(s.primaryOrSecondary!==(s.sourceType.startsWith('PRIMARY')?'PRIMARY':'SECONDARY'))fail(s.sourceId,'secondary source falsely primary');try{const u=new URL(s.resolvedURL??s.url);if(u.protocol!=='https:'||u.username||u.password||!s.allowedRoutes.some(r=>r.host===u.hostname&&u.pathname.startsWith(r.prefix)))fail(s.sourceId,'unqualified official route');}catch{fail(s.sourceId,'invalid URL');}}
  for(const e of b.entities)if(!b.comparabilityRules.entityTypes.includes(e.entityType))fail(e.id,'invalid entity type');
  for(const c of b.claims){ref(c.caseId,'projects',c.claimId);ref(c.scopeId,'scopes',c.claimId);ref(c.entityId,'entities',c.claimId,true);ref(c.previousClaimId,'claims',c.claimId,true);if(!c.sourceIds.length||!c.sourceLocator||!c.definition)fail(c.claimId,'claim provenance missing');for(const s of c.sourceIds)ref(s,'sources',c.claimId);if(!LAYERS.includes(c.panelLayer))fail(c.claimId,'invalid layer');if(c.effectiveDate!==null&&!validDate(c.effectiveDate))fail(c.claimId,'invalid effective clock');if((c.value===null)!==(c.evidenceClass==='UNAVAILABLE')||(c.value===null)!==(c.observedOrEstimated==='UNAVAILABLE'))fail(c.claimId,'UNAVAILABLE fabricated');if(c.evidenceClass.startsWith('PRIMARY')&&!c.sourceIds.some(s=>maps.sources.get(s)?.primaryOrSecondary==='PRIMARY'))fail(c.claimId,'secondary upgraded to primary');if(c.sourceIds.every(s=>maps.sources.get(s)?.primaryOrSecondary==='SECONDARY')&&c.value!==null&&!['SECONDARY_REPORTED','SECONDARY_ESTIMATE'].includes(c.observedOrEstimated))fail(c.claimId,'secondary falsely observed');if(/^[A-Z]{3}_/.test(c.unit)?(c.currency!==c.unit.split('_')[0]||typeof c.value!=='number'):c.currency!==null)fail(c.claimId,'currency/unit mismatch');if(c.unit==='PERCENT'&&(typeof c.value!=='number'||c.value<0||c.value>100))fail(c.claimId,'ownership/percentage outside bounds');if(!b.comparabilityRules.units.includes(c.unit))fail(c.claimId,'invalid native unit');if(/cost|development-estimate|pledge|regional-plan|development-plan/.test(c.field)&&c.unit.endsWith('_BILLION')&&/estimate|plan|pledge|commitment/i.test(c.definition)&&c.observedOrEstimated==='OBSERVED_REPORTED')fail(c.claimId,'estimated cost falsely observed');if(c.capacityDefinition&&/PLANNED/.test(c.capacityDefinition)&&/operational|live-capacity/.test(c.field))fail(c.claimId,'planned capacity mislabeled operational');if(['MW','GW'].includes(c.unit)!==(c.capacityDefinition!==null))fail(c.claimId,'capacity native definition missing');if(c.unit==='ENTITY')ref(c.value,'entities',c.claimId);if(c.previousClaimId){const prev=maps.claims.get(c.previousClaimId);if(prev&&(prev.caseId!==c.caseId||(c.recordState!=='RESTATED'&&prev.effectiveDate&&c.effectiveDate&&prev.effectiveDate>=c.effectiveDate)||(c.recordState==='RESTATED'&&claimClock(c,maps.sources)<=claimClock(prev,maps.sources))))fail(c.claimId,'revision/status chronology');}}
  for(const projectId of ['hyperion','el-paso']){const rows=b.claims.filter(c=>c.caseId===projectId&&c.unit==='PERCENT'&&/^(ownership-|meta-interest|fund-interest)/.test(c.field));if(rows.length&&rows.reduce((n,c)=>n+c.value,0)!==100)fail(projectId,'complete ownership not100');if(rows.some(c=>maps.entities.get(c.entityId)?.entityType==='FUND_MANAGER'))fail(projectId,'fund manager not owner');}
  const ownershipGroups=new Map();
  for(const c of b.claims.filter(c=>c.unit==='PERCENT'&&/^(ownership-|meta-interest|fund-interest)/.test(c.field))){const key=JSON.stringify([c.caseId,c.scopeId,c.effectiveDate,c.sourceIds.slice().sort()]);const sum=(ownershipGroups.get(key)??0)+c.value;ownershipGroups.set(key,sum);if(sum>100)fail(c.caseId,'ownership group exceeds100');}
  const targets=new Set([...maps.entities.keys(),...maps.projects.keys()]);
  for(const r of b.relationships){ref(r.fromId,'entities',r.id);if(!targets.has(r.toId))fail(r.id,'unknown relationship target');ref(r.claimId,'claims',r.id);const c=maps.claims.get(r.claimId);if(!c||c.caseId!==r.projectId||c.value?.fromId!==r.fromId||c.value?.toId!==r.toId||c.value?.type!==r.relationshipType)fail(r.id,'unsupported relationship/co-mention');if(!b.comparabilityRules.relationshipTypes.includes(r.relationshipType))fail(r.id,'unsupported relationship type');}
  for(const p of b.projects){if(p.actualOperationalDate&&!validDate(p.actualOperationalDate))fail(p.id,'invalid actual operational date');if(!p.companyIds.every(c=>COMPANIES.includes(c)))fail(p.id,'company outside universe');for(const id of [p.locationClaimId,...p.statusClaimIds,...p.materialClaimIds,...p.relationshipClaimIds])ref(id,'claims',p.id);if(!b.comparabilityRules.archetypes.includes(p.primaryArchetype))fail(p.id,'unknown archetype');}
  for(const n of ['financing','obligations','power'])for(const r of b[n]){ref(r.projectId,'projects',r.id);for(const id of r.claimIds)ref(id,'claims',r.id);for(const field of ['issuerId','obligorId','beneficiaryId','utilityId'])if(field in r)ref(r[field],'entities',r.id,true);}
  for(const [n,key] of [['financing','instrumentIdentity'],['obligations','obligationIdentity']]){const identities=b[n].map(r=>r[key]);if(new Set(identities).size!==identities.length)fail(n,'same instrument/obligation duplicated');}
  for(const s of b.scopes){ref(s.caseId,'projects',s.scopeId);for(const id of [...s.comparableTo,...s.notComparableTo])ref(id,'scopes',s.scopeId);for(const id of s.sourceIds)ref(id,'sources',s.scopeId);}
  const walk=v=>{if(Array.isArray(v))return v.forEach(walk);if(v&&typeof v==='object')for(const [k,x]of Object.entries(v)){if(/^(aiRoi|roi|roic|irr|npv|payback|hiddenDebt|hiddenLeverageScore|systemicRiskScore|totalAiInvestment|aggregateInvestment)$/i.test(k)||k==='field'&&/^(aiRoi|hiddenDebt|totalAiInvestment|systemicRiskScore)$/i.test(x))fail(k,'prohibited aggregate/return');walk(x);}};walk(b);
  return errors;
}
const metricFor=c=>['status','project-status'].includes(c.field)?'PROJECT_STATUS':c.field.replace(/[^a-z0-9]+/gi,'_').toUpperCase();
const definitionFor=c=>({metricId:metricFor(c),layer:c.panelLayer,unit:c.unit,nativeDefinition:c.definition,capacityDefinition:c.capacityDefinition,classification:c.observedOrEstimated,comparisonBasis:['status','project-status'].includes(c.field)?'PREDECLARED_STATUS_VOCABULARY':c.definition});
function claimClock(c,sources){return c.sourceIds.map(id=>sources.get(id)?.availableFrom).sort().at(-1);}
export function admit(p,claims,sources,asOf){
  const available=id=>{const c=claims.get(id);return c&&claimClock(c,sources)<=asOf;};
  const primary=p.admissionSourceIds.some(id=>sources.get(id)?.primaryOrSecondary==='PRIMARY'&&sources.get(id).availableFrom<=asOf&&sources.get(id).qualificationStatus!=='UNQUALIFIED');
  const location=claims.get(p.locationClaimId);
  const passed=primary&&location?.value!==null&&available(p.locationClaimId)&&p.statusClaimIds.some(available)&&p.relationshipClaimIds.some(available)&&p.materialClaimIds.some(id=>available(id)&&claims.get(id)?.value!==null);
  return {state:passed?'QUALIFIED_PROJECT':'CANDIDATE_PROJECT',reason:passed?'Primary site/company relationship/status-or-explicit-unknown/material attribute/scope/provenance gate satisfied':'Insufficient as-of primary evidence or field-level admission requirements'};
}
export function eligibility(o,sources,b){
  if(o.value===null)return 'NOT_PUBLIC';
  if(o.recordState==='CONFLICT_REQUIRES_REVIEW'||o.qualificationStatus==='REVIEW_REQUIRED'||o.qualificationStatus==='CONFLICTING')return 'REVIEW_REQUIRED';
  const docs=o.sourceIds.map(id=>sources.get(id));
  if(o.evidenceClass!=='PRIMARY_VERIFIED'||o.qualificationStatus!=='QUALIFIED'||o.condition||o.capacityDefinition==='UNKNOWN'||docs.some(s=>!s?.sourceHash||s.qualificationStatus!=='ARCHIVED_REVIEWED'))return 'RESEARCH_ONLY';
  if(o.unit==='ENTITY'||o.unit==='RELATIONSHIP'||/ENTITY_|OWNER|OWNERSHIP|LEGAL|EDGE_|DEVELOPER|TENANT/.test(o.metricId)||!b.publicationRules.safeFamilies.includes(o.fieldFamily)||o.overlapStatus!=='NO_KNOWN_OVERLAP')return 'RESEARCH_ONLY';
  return 'PUBLIC_READY';
}
export function build(b,{asOf}={}){
  if(!validDate(asOf))throw Error('Explicit valid asOf date required');
  const errors=inputErrors(b);if(errors.length)throw Error(errors.join('\n'));
  const claims=map(b.claims),sources=map(b.sources),scopes=map(b.scopes);
  const availableClaims=b.claims.filter(c=>claimClock(c,sources)<=asOf);
  const eligibleIds=new Set(availableClaims.map(c=>c.claimId));
  const projects=b.projects.map(p=>({...p,admission:admit(p,claims,sources,asOf)})).filter(p=>p.admission.state==='QUALIFIED_PROJECT').map(p=>({...p,statusClaimIds:p.statusClaimIds.filter(id=>eligibleIds.has(id)),materialClaimIds:p.materialClaimIds.filter(id=>eligibleIds.has(id)),relationshipClaimIds:p.relationshipClaimIds.filter(id=>eligibleIds.has(id)),admissionSourceIds:p.admissionSourceIds.filter(id=>sources.get(id)?.availableFrom<=asOf)}));
  const projectIds=new Set(projects.map(p=>p.id)),activeClaims=availableClaims.filter(c=>projectIds.has(c.caseId));
  const definitions=[...new Map(activeClaims.map(c=>{const d=definitionFor(c),id='def:'+hash(d).slice(0,20);return [id,{definitionId:id,...d}];})).values()].sort((a,z)=>a.definitionId.localeCompare(z.definitionId));
  const observations=activeClaims.map(c=>{
    const layer=c.panelLayer,fieldFamily=familyFor(c,layer),monetary=/^[A-Z]{3}_/.test(c.unit),conflict=c.recordState==='CONFLICT_REQUIRES_REVIEW'||b.conflicts.some(x=>x.claimIds.includes(c.claimId));
    const sourceMeta=c.sourceIds.map(id=>sources.get(id));const allArchived=sourceMeta.every(s=>s.sourceHash&&s.qualificationStatus==='ARCHIVED_REVIEWED');
    const definitionId='def:'+hash(definitionFor(c)).slice(0,20),sourceVintage='sv:'+hash(sourceMeta.map(s=>s.sourceVersion).sort());
    const period=c.periodOverride??{basis:c.effectiveDate?'SOURCE_REPORTED_EFFECTIVE_DATE':'NOT_DISCLOSED',start:c.effectiveDate,end:c.effectiveDate};
    const entityId=c.entityId??'unknown:'+c.caseId;
    const key={projectId:c.caseId,entityId,layer,metricId:metricFor(c),definitionId,scopeId:c.scopeId,period,sourceVintage};
    const o={observationId:'obs:'+hash({...key,claimId:c.claimId}).slice(0,24),...key,claimId:c.claimId,sourceIds:c.sourceIds,sourceVersions:sourceMeta.map(s=>s.sourceVersion),sourceHashes:sourceMeta.map(s=>s.sourceHash),documentDates:sourceMeta.map(s=>s.documentDate),availableFrom:claimClock(c,sources),sourceLocator:c.sourceLocator,value:c.value,unit:c.unit,currency:c.currency,operator:c.operator,capacityDefinition:c.capacityDefinition,nativeDefinition:c.definition,observedOrEstimated:c.observedOrEstimated,evidenceClass:conflict?'CONFLICTING_EVIDENCE':c.evidenceClass,qualificationStatus:c.value===null?'UNAVAILABLE':conflict?'CONFLICTING':c.evidenceClass==='PRIMARY_VERIFIED'&&allArchived?'QUALIFIED':c.evidenceClass==='PRIMARY_PARTIAL'?'PARTIAL':'REVIEW_REQUIRED',recordState:conflict?'CONFLICT_REQUIRES_REVIEW':c.recordState,fieldFamily,overlapStatus:monetary?'UNRESOLVED':fieldFamily==='capacity'&&c.capacityDefinition==='UNKNOWN'?'UNRESOLVED':'NO_KNOWN_OVERLAP',previousClaimId:c.previousClaimId,condition:c.condition,comparabilityStatus:c.capacityDefinition==='UNKNOWN'?'UNKNOWN':monetary?'NOT_COMPARABLE':fieldFamily==='status'?'LIMITED_COMPARABILITY':'UNKNOWN',publicationEligibility:'NOT_PUBLIC'};
    o.publicationEligibility=eligibility(o,sources,b);return o;
  }).sort((a,z)=>a.observationId.localeCompare(z.observationId));
  const statusHistory=observations.filter(o=>o.metricId==='PROJECT_STATUS').map(o=>({id:'status:'+o.observationId,projectId:o.projectId,scopeId:o.scopeId,status:o.value??'UNKNOWN',effectiveAt:o.period.start,reportedAt:o.documentDates.filter(Boolean).sort().at(-1)??null,availableFrom:o.availableFrom,sourceIds:o.sourceIds,claimId:o.claimId,observationId:o.observationId,recordState:o.recordState,qualificationStatus:o.qualificationStatus,statusSeries:'SOURCE_SCOPE_STAGE_NOT_NATIONAL_OR_FULL_CAMPUS_TOTAL'})).sort((a,z)=>(a.effectiveAt??'').localeCompare(z.effectiveAt??'')||a.id.localeCompare(z.id));
  for(const h of statusHistory){if(h.recordState==='CURRENT'&&statusHistory.some(z=>z.projectId===h.projectId&&z.scopeId===h.scopeId&&z.effectiveAt>h.effectiveAt&&z.status!=='UNKNOWN'))h.recordState='SUPERSEDED';}
  // A newer claim changes historical record state only for an explicitly linked restatement or same-series design revision. Distinct dated stocks remain separate observations.
  for(const o of observations){const newer=observations.find(z=>z.previousClaimId===o.claimId&&z.metricId===o.metricId&&z.scopeId===o.scopeId&&z.layer===o.layer);if(newer&&o.fieldFamily!=='status'&&o.period.start!==null&&o.period.start===newer.period.start)o.recordState='SUPERSEDED';if(newer&&o.metricId==='POWER_DESIGN')o.recordState='SUPERSEDED';o.publicationEligibility=eligibility(o,sources,b);if(o.recordState==='SUPERSEDED'&&o.publicationEligibility==='PUBLIC_READY')o.publicationEligibility='RESEARCH_ONLY';}
  const pairs=[];for(const p of projects){const money=observations.filter(o=>o.projectId===p.id&&o.value!==null&&/^[A-Z]{3}_/.test(o.unit));for(let i=0;i<money.length;i++)for(let j=i+1;j<money.length;j++)pairs.push({id:'dna:'+hash([money[i].observationId,money[j].observationId].sort()).slice(0,20),leftObservationId:money[i].observationId,rightObservationId:money[j].observationId,projectId:p.id,relation:money[i].scopeId===money[j].scopeId&&money[i].layer!==money[j].layer?'SAME_ASSET_DIFFERENT_LAYER':'UNRESOLVED',decision:'DO_NOT_ADD',reason:'Different concepts, sources or vintages may represent overlapping assets; non-overlap not qualified'});}
  const relationships=b.relationships.filter(r=>projectIds.has(r.projectId)&&eligibleIds.has(r.claimId));
  const scopedIds=new Set(observations.map(o=>o.scopeId));const usedSourceIds=new Set(activeClaims.flatMap(c=>c.sourceIds));const usedEntityIds=new Set([...observations.map(o=>o.entityId),...relationships.flatMap(r=>[r.fromId,r.toId])]);
  const admittedFin=b.financing.filter(r=>projectIds.has(r.projectId)&&r.claimIds.some(id=>eligibleIds.has(id))).map(r=>({...r,claimIds:r.claimIds.filter(id=>eligibleIds.has(id))}));
  const admittedOb=b.obligations.filter(r=>projectIds.has(r.projectId)&&r.claimIds.some(id=>eligibleIds.has(id))).map(r=>({...r,claimIds:r.claimIds.filter(id=>eligibleIds.has(id))}));
  const admittedPower=b.power.filter(r=>projectIds.has(r.projectId)&&r.claimIds.some(id=>eligibleIds.has(id))).map(r=>({...r,claimIds:r.claimIds.filter(id=>eligibleIds.has(id))}));
  for(const r of [...admittedFin,...admittedOb,...admittedPower])for(const k of ['issuerId','obligorId','beneficiaryId','utilityId'])if(r[k])usedEntityIds.add(r[k]);
  const operationalSources=b.sources.filter(s=>usedSourceIds.has(s.sourceId));
  const economicSources=operationalSources.map(({retrievedAt,retrievalStatus,accessError,reviewMethod,...s})=>s);
  const result={methodology:{...b.methodology,asOfDate:asOf},projects,entities:b.entities.filter(e=>usedEntityIds.has(e.id)).map(e=>({...e,claimIds:e.claimIds.filter(id=>eligibleIds.has(id))})),observations,definitions,scopes:b.scopes.filter(s=>scopedIds.has(s.scopeId)).map(s=>({...s,sourceIds:s.sourceIds.filter(id=>usedSourceIds.has(id)),comparableTo:s.comparableTo.filter(id=>scopedIds.has(id)),notComparableTo:s.notComparableTo.filter(id=>scopedIds.has(id))})),claims:activeClaims,relationships,statusHistory,financing:admittedFin,obligations:admittedOb,power:admittedPower,sources:economicSources,overlaps:{aggregationAllowed:false,DO_NOT_ADD_PAIRS:pairs,legacyPairCount:b.legacyOverlaps.DO_NOT_ADD_PAIRS.length},conflicts:b.conflicts.filter(c=>c.claimIds.some(id=>eligibleIds.has(id))),comparabilityRules:b.comparabilityRules,publicationRules:b.publicationRules};
  result.panelHash=hash(result);result.views=derive(result,b.screening.filter(s=>s.availableFrom<=asOf));
  const qualified=validatePanel(result,b);if(!qualified.valid)throw Error(qualified.errors.join('\n'));
  return result;
}
export function compare(a,z,panel){
  const reasons=[];const defs=new Map(panel.definitions.map(d=>[d.definitionId,d])),scopes=new Map(panel.scopes.map(s=>[s.scopeId,s]));
  if(a.value===null||z.value===null)reasons.push('UNAVAILABLE');
  if(!['QUALIFIED','PARTIAL'].includes(a.qualificationStatus)||!['QUALIFIED','PARTIAL'].includes(z.qualificationStatus))reasons.push('UNQUALIFIED_OR_CONFLICTING');
  if(a.metricId!==z.metricId)reasons.push('METRIC');if(a.layer!==z.layer)reasons.push('ENTITY_LAYER');if(a.unit!==z.unit||a.currency!==z.currency)reasons.push('NATIVE_UNIT_CURRENCY');if(a.period.basis!==z.period.basis)reasons.push('PERIOD_BASIS');
  const categorical=a.metricId==='PROJECT_STATUS'&&z.metricId==='PROJECT_STATUS';
  if(scopes.get(a.scopeId)?.notComparableTo.includes(z.scopeId)||scopes.get(z.scopeId)?.notComparableTo.includes(a.scopeId))reasons.push('EXPLICIT_INCOMPATIBLE_SCOPE');
  if(!categorical){if(a.definitionId!==z.definitionId)reasons.push('NATIVE_DEFINITION');if(a.capacityDefinition!==z.capacityDefinition||a.capacityDefinition==='UNKNOWN')reasons.push('CAPACITY_DEFINITION');if(a.scopeId!==z.scopeId&&!scopes.get(a.scopeId)?.comparableTo.includes(z.scopeId))reasons.push('SCOPE');if(a.entityId!==z.entityId)reasons.push('REPORTING_ENTITY');if(JSON.stringify(a.period)!==JSON.stringify(z.period))reasons.push('PERIOD');if(a.observedOrEstimated!==z.observedOrEstimated)reasons.push('ESTIMATE_VS_REPORTED');}
  else if(defs.get(a.definitionId)?.comparisonBasis!=='PREDECLARED_STATUS_VOCABULARY'||defs.get(z.definitionId)?.comparisonBasis!=='PREDECLARED_STATUS_VOCABULARY')reasons.push('STATUS_VOCABULARY');
  if(reasons.length)return {status:'NOT_COMPARABLE',reasons:[...new Set(reasons)]};
  return {status:categorical&&a.period.start!==z.period.start?'LIMITED_COMPARABILITY':'COMPARABLE',reasons:categorical?['SOURCE_DATED_CATEGORY_ONLY_NO_CAPACITY_OR_FINANCIAL_RANK']:[]};
}
export function assertAddable(){throw Error('DO_NOT_ADD: Phase3C exposes no financial aggregation API; non-overlap qualification is required in a later methodology.');}
export function derive(p,screening=[]){
  const families=['physical','status','legalOwner','capacity','financing','obligations','accounting','power','monetization'];
  const companyCoverage=COMPANIES.map(companyId=>{const ps=p.projects.filter(x=>x.companyIds.includes(companyId)),ids=new Set(ps.map(x=>x.id)),os=p.observations.filter(o=>ids.has(o.projectId));return {companyId,qualifiedProjects:ps.map(x=>x.id),candidateProjects:screening.filter(x=>x.companyId===companyId&&x.state==='CANDIDATE_PROJECT').map(x=>x.projectId),rejectedProjects:screening.filter(x=>x.companyId===companyId&&x.state==='REJECTED_PROJECT').map(x=>x.projectId),primarySources:[...new Set(os.flatMap(o=>o.sourceIds))].filter(id=>p.sources.find(s=>s.sourceId===id)?.primaryOrSecondary==='PRIMARY'),secondarySources:[...new Set(os.flatMap(o=>o.sourceIds))].filter(id=>p.sources.find(s=>s.sourceId===id)?.primaryOrSecondary==='SECONDARY'),qualifiedObservations:os.filter(o=>o.qualificationStatus==='QUALIFIED').length,unavailableObservations:os.filter(o=>o.value===null).length,statuses:ps.map(pr=>({projectId:pr.id,history:p.statusHistory.filter(h=>h.projectId===pr.id)})),archetypes:[...new Set(ps.map(x=>x.primaryArchetype))],knownLeaseExposureProjects:ps.filter(pr=>os.some(o=>o.projectId===pr.id&&o.layer==='ECONOMIC_OBLIGATION'&&o.value!==null&&/LEASE/.test(o.metricId))).map(x=>x.id),knownDebtDisclosureProjects:ps.filter(pr=>p.financing.some(f=>f.projectId===pr.id&&!/pledge|fund-cash/.test(f.instrumentIdentity))).map(x=>x.id),knownGuaranteeProjects:ps.filter(pr=>os.some(o=>o.projectId===pr.id&&o.value!==null&&/RVG|GUARANTEE/.test(o.metricId))).map(x=>x.id),sourceCoverage:families.map(f=>({family:f,observations:os.filter(o=>o.fieldFamily===f).length,primaryVerified:os.filter(o=>o.fieldFamily===f&&o.evidenceClass==='PRIMARY_VERIFIED').length,primaryPartial:os.filter(o=>o.fieldFamily===f&&o.evidenceClass==='PRIMARY_PARTIAL').length,secondaryOnly:os.filter(o=>o.fieldFamily===f&&o.evidenceClass==='SECONDARY_ONLY').length,unavailable:os.filter(o=>o.fieldFamily===f&&o.value===null).length})),majorSourceGaps:families.filter(f=>!os.some(o=>o.fieldFamily===f&&o.qualificationStatus==='QUALIFIED'&&o.value!==null)),minimumTwoProjectTargetMet:ps.length>=2};});
  const denominator=p.projects.length,missingness=['legalOwner','financing','power','obligations','monetization'].map(f=>{const withQualified=p.projects.filter(pr=>p.observations.some(o=>o.projectId===pr.id&&o.fieldFamily===f&&o.qualificationStatus==='QUALIFIED'&&o.value!==null)).length;return {fieldFamily:f,definition:'Projects with at least one qualified disclosed field in this family; not proof of complete contract/terms',denominator,withAtLeastOneQualifiedField:withQualified,withoutQualifiedField:denominator-withQualified,coveragePercent:denominator?100*withQualified/denominator:null};});
  const countBy=field=>Object.fromEntries([...new Set(p.observations.map(o=>o[field]))].sort().map(k=>[k,p.observations.filter(o=>o[field]===k).length]));
  return {companyCoverage,missingness,evidenceCounts:countBy('evidenceClass'),qualificationCounts:countBy('qualificationStatus'),publicationCounts:countBy('publicationEligibility'),projectCapitalStructure:p.projects.map(pr=>({projectId:pr.id,archetype:pr.primaryArchetype,financingIds:p.financing.filter(f=>f.projectId===pr.id).map(f=>f.id),obligationIds:p.obligations.filter(f=>f.projectId===pr.id).map(f=>f.id),noDollarTotal:true})),projectPower:p.projects.map(pr=>({projectId:pr.id,powerRecordIds:p.power.filter(f=>f.projectId===pr.id).map(f=>f.id),claimIds:p.observations.filter(o=>o.projectId===pr.id&&o.layer==='POWER_INFRASTRUCTURE').map(o=>o.claimId)}))};
}
export function validatePanel(p,b){
  const errors=[],fail=(id,m)=>errors.push(`${id}: ${m}`);
  errors.push(...schemaErrors(p.observations,read('schemas/observations.schema.json'),'observations'));
  const ids=new Set(),keys=new Set(),claims=map(p.claims),sources=map(p.sources),projects=map(p.projects),entities=map(p.entities),defs=new Map(p.definitions.map(d=>[d.definitionId,d])),scopes=map(p.scopes);
  for(const o of p.observations){if(ids.has(o.observationId))fail(o.observationId,'duplicate observation');ids.add(o.observationId);const key=JSON.stringify(canonical({projectId:o.projectId,entityId:o.entityId,layer:o.layer,metricId:o.metricId,definitionId:o.definitionId,scopeId:o.scopeId,period:o.period,sourceVintage:o.sourceVintage}));if(keys.has(key))fail(o.observationId,'duplicate fundamental key');keys.add(key);if(!projects.has(o.projectId)||!entities.has(o.entityId)||!scopes.has(o.scopeId)||!defs.has(o.definitionId)||!claims.has(o.claimId))fail(o.observationId,'unknown observation reference');const c=claims.get(o.claimId);if(c&&['value','unit','currency','sourceLocator','observedOrEstimated'].some(k=>JSON.stringify(o[k])!==JSON.stringify(c[k])))fail(o.observationId,'claim/observation mismatch');if(o.availableFrom>p.methodology.asOfDate||o.documentDates.some(d=>d!==null&&d>p.methodology.asOfDate))fail(o.observationId,'future source leakage');if(o.period.start&&o.period.start>p.methodology.asOfDate&&!['MANAGEMENT_GUIDANCE','CONTRACTUAL_COMMITMENT','PROJECT_ESTIMATE'].includes(o.observedOrEstimated))fail(o.observationId,'future observation leakage');if(o.sourceVersions.length!==o.sourceIds.length||o.sourceHashes.length!==o.sourceIds.length||o.documentDates.length!==o.sourceIds.length||o.sourceIds.some((id,i)=>o.sourceVersions[i]!==sources.get(id)?.sourceVersion||o.sourceHashes[i]!==sources.get(id)?.sourceHash||o.documentDates[i]!==sources.get(id)?.documentDate)||o.sourceVintage!=='sv:'+hash(o.sourceVersions.slice().sort()))fail(o.observationId,'source vintage mismatch');if(o.sourceIds.some(id=>!sources.has(id)))fail(o.observationId,'source missing');if(o.publicationEligibility!==eligibility(o,sources,b)&&!(o.recordState==='SUPERSEDED'&&o.publicationEligibility==='RESEARCH_ONLY'))fail(o.observationId,'publication eligibility invalid');if(o.metricId==='PROJECT_STATUS'&&o.value!==null&&!STATES.includes(o.value))fail(o.observationId,'invalid status');}
  for(const pr of p.projects){const hs=p.statusHistory.filter(h=>h.projectId===pr.id);const construction=hs.filter(h=>h.status==='UNDER_CONSTRUCTION'&&h.effectiveAt).map(h=>h.effectiveAt).sort()[0];if(construction&&hs.some(h=>['OPERATIONAL','PARTIALLY_OPERATIONAL'].includes(h.status)&&h.effectiveAt&&h.effectiveAt<construction))fail(pr.id,'operational before construction inconsistency');if(pr.actualOperationalDate&&pr.actualOperationalDate>p.methodology.asOfDate)fail(pr.id,'future actual operational date');}
  const pairs=new Set(p.overlaps.DO_NOT_ADD_PAIRS.map(x=>[x.leftObservationId,x.rightObservationId].sort().join('|')));
  for(const pr of p.projects){const money=p.observations.filter(o=>o.projectId===pr.id&&/^[A-Z]{3}_/.test(o.unit)&&o.value!==null);for(let i=0;i<money.length;i++)for(let j=i+1;j<money.length;j++)if(!pairs.has([money[i].observationId,money[j].observationId].sort().join('|')))fail(pr.id,'DO_NOT_ADD missing');}
  for(const pair of p.overlaps.DO_NOT_ADD_PAIRS)if(!ids.has(pair.leftObservationId)||!ids.has(pair.rightObservationId)||pair.decision!=='DO_NOT_ADD')fail(pair.id,'overlap reference/decision');
  const {panelHash,views,...content}=p;if(hash(content)!==panelHash)fail('panel','content identity mismatch');if(JSON.stringify(canonical(p.views))!==JSON.stringify(canonical(derive(p,b.screening.filter(s=>s.availableFrom<=p.methodology.asOfDate)))))fail('views','derived views differ from qualified panel');
  return {valid:!errors.length,errors};
}
export function summary(p,b){const v=validatePanel(p,b);return {...v,asOfDate:p.methodology.asOfDate,panelHash:p.panelHash,counts:Object.fromEntries(['projects','entities','relationships','observations','claims','definitions','scopes','statusHistory','financing','obligations','power','sources'].map(n=>[n,p[n].length])),overlapRecords:p.overlaps.DO_NOT_ADD_PAIRS.length,evidenceCounts:p.views.evidenceCounts,publicationCounts:p.views.publicationCounts,companyCoverage:p.views.companyCoverage.map(c=>({companyId:c.companyId,qualifiedProjects:c.qualifiedProjects,candidateProjects:c.candidateProjects,rejectedProjects:c.rejectedProjects,majorSourceGaps:c.majorSourceGaps}))};}
export function writePanel(p){
  // Fixed research output whitelist; no arbitrary user path and no src/public writes.
  const snapshotDir=path.join(root,'snapshots',p.methodology.asOfDate,p.panelHash);fs.mkdirSync(snapshotDir,{recursive:true});const snapshotBytes=JSON.stringify(canonical(p),null,2)+'\n',snapshotFile=path.join(snapshotDir,'panel.json');if(fs.existsSync(snapshotFile)){if(fs.readFileSync(snapshotFile,'utf8')!==snapshotBytes)throw Error('Immutable snapshot identity collision');}else fs.writeFileSync(snapshotFile,snapshotBytes,{flag:'wx'});
  const outputs={observations:p.observations,projects:p.projects,entities:p.entities,relationships:p.relationships,definitions:p.definitions,scopes:p.scopes,claims:p.claims,overlaps:p.overlaps,'status-history':p.statusHistory,financing:p.financing,obligations:p.obligations,power:p.power,sources:p.sources,methodology:{...p.methodology,panelHash:p.panelHash},'derived-views':p.views,conflicts:p.conflicts};
  const provenance=loadInput().sources.filter(s=>p.sources.some(x=>x.sourceVersion===s.sourceVersion)).map(s=>({sourceId:s.sourceId,sourceVersion:s.sourceVersion,retrievedAt:s.retrievedAt,retrievalStatus:s.retrievalStatus,accessError:s.accessError}));fs.writeFileSync(path.join(root,'provenance-receipts.json'),JSON.stringify(canonical(provenance),null,2)+'\n');
  for(const [name,value]of Object.entries(outputs))fs.writeFileSync(path.join(root,name+'.json'),JSON.stringify(canonical(value),null,2)+'\n');

  fs.writeFileSync(path.join(root,'migration-map.json'),JSON.stringify(p.claims.filter(c=>!c.claimId.includes(':3c:')).map(c=>({phase3bClaimId:c.claimId,panelObservationIds:p.observations.filter(o=>o.claimId===c.claimId).map(o=>o.observationId),transformation:'ADDITIVE_LAYER/VINTAGE_MAPPING; ORIGINAL_VALUE_RETAINED'})),null,2)+'\n');
}
