import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {loadInput,build,validatePanel,summary,inputErrors,compare,assertAddable,writePanel,hash,root,COMPANIES} from '../panel/scripts/panel.mjs';
const ASOF='2026-10-07',fresh=()=>structuredClone(loadInput()),panel=b=>build(b??fresh(),{asOf:ASOF});
const claim=(b,id)=>b.claims.find(c=>c.claimId===id);
const obs=(p,id)=>p.observations.find(o=>o.claimId===id);
const bad=(mutate,rx)=>{const b=fresh();mutate(b);assert.throws(()=>panel(b),rx);};
const invalid=(mutate,rx)=>{const b=fresh(),p=panel(b);mutate(p);const r=validatePanel(p,b);assert.equal(r.valid,false);assert.match(r.errors.join('\n'),rx);};
test('all five core companies have two admitted sites; PF1 stays a comparative case',()=>{const b=fresh(),p=panel(b),s=summary(p,b);assert.equal(s.valid,true,s.errors.join('\n'));assert.equal(p.projects.length,11);assert.deepEqual(p.views.companyCoverage.map(c=>c.companyId),COMPANIES);for(const c of p.views.companyCoverage)assert.equal(c.qualifiedProjects.length,2);assert.equal(p.projects.find(p=>p.id==='polaris-forge-1').companyIds.length,0);});
test('fundamental grain includes project/entity/layer/metric/native definition/scope/vintage/period',()=>{for(const o of panel().observations)for(const k of ['projectId','entityId','layer','metricId','definitionId','scopeId','sourceVintage','period'])assert.ok(o[k]);});
test('explicit asOf is mandatory; impossible date rejected',()=>{assert.throws(()=>build(fresh()),/Explicit valid/);assert.throws(()=>build(fresh(),{asOf:'2026-02-30'}),/Explicit valid/);});
test('earlier disclosure snapshot excludes future accounting, current undated pages and new company sites',()=>{const p=build(fresh(),{asOf:'2025-10-31'});assert.ok(p.projects.some(p=>p.id==='hyperion'));assert.equal(p.observations.some(o=>o.claimId==='hyperion:maximum-exposure-2026'),false);assert.equal(p.projects.some(p=>p.id==='el-paso'||p.id==='google-red-oak'),false);assert.ok(p.observations.every(o=>o.availableFrom<='2025-10-31'));});
test('unqualified government/challenge source is not project admission evidence',()=>{const b=fresh();const p=b.projects.find(p=>p.id==='aws-canton');p.admissionSourceIds=['madison-eda'];assert.equal(panel(b).projects.some(p=>p.id==='aws-canton'),false);});
test('missing meaningful site attribute leaves candidate unqualified',()=>{const b=fresh();b.projects.find(p=>p.id==='google-red-oak').materialClaimIds=[];assert.equal(panel(b).projects.some(p=>p.id==='google-red-oak'),false);});
test('unknown operating status remains explicit missingness rather than fabricated operation',()=>{const p=panel();for(const id of ['google-midlothian','google-red-oak','aws-canton'])assert.ok(p.statusHistory.some(h=>h.projectId===id&&h.status==='UNKNOWN'&&h.qualificationStatus==='UNAVAILABLE'));});
test('construction/partial-operation history retained for all three frozen cases',()=>{const p=panel();for(const id of ['fairwater','polaris-forge-1']){const hs=p.statusHistory.filter(h=>h.projectId===id);assert.ok(hs.some(h=>h.status==='UNDER_CONSTRUCTION'));assert.ok(hs.some(h=>h.status==='PARTIALLY_OPERATIONAL'));}assert.ok(p.statusHistory.filter(h=>h.projectId==='hyperion').length>=2);});
test('unknown date is not replaced with processing date',()=>{const p=panel();const o=p.observations.find(o=>o.projectId==='google-red-oak'&&o.metricId==='LOCATION');assert.deepEqual(o.period,{basis:'NOT_DISCLOSED',start:null,end:null});assert.equal(o.availableFrom,ASOF);});
test('planned future online year is guidance, not actual opening',()=>{const p=panel(),o=p.observations.find(o=>o.metricId==='EXPECTED_ONLINE_YEAR');assert.equal(o.value,2028);assert.equal(o.observedOrEstimated,'MANAGEMENT_GUIDANCE');assert.equal(p.projects.find(p=>p.id==='el-paso').actualOperationalDate,null);});
test('native capacity and cost distinctions survive migration unchanged',()=>{const p=panel();assert.equal(obs(p,'hyperion:financed-capacity').value,2.064);assert.equal(obs(p,'hyperion:financed-capacity').capacityDefinition,'UNKNOWN');assert.equal(obs(p,'hyperion:planned-capacity').value,5);assert.equal(obs(p,'hyperion:regional-plan').operator,'GT');assert.equal(obs(p,'hyperion:cost').observedOrEstimated,'PROJECT_ESTIMATE');});
test('Hyperion 5GW and ElPaso compute1GW are not harmonized capacity denominators',()=>{const p=panel();assert.equal(compare(obs(p,'hyperion:planned-capacity'),p.observations.find(o=>o.projectId==='el-paso'&&o.metricId==='PLANNED_CAPACITY'),p).status,'NOT_COMPARABLE');});
test('Hyperion financing and Fairwater corporate investment pledge reject direct comparison',()=>{const p=panel();assert.equal(compare(obs(p,'hyperion:offering'),obs(p,'fairwater:pledge'),p).status,'NOT_COMPARABLE');});
test('lease, guarantee threshold and maximum exposure cannot rank as debt',()=>{const p=panel();for(const id of ['hyperion:lease-commitment','hyperion:rvg-threshold','hyperion:maximum-exposure-2026'])assert.equal(compare(obs(p,id),obs(p,'hyperion:offering'),p).status,'NOT_COMPARABLE');});
test('27bn and50bn+ scopes remain not comparable',()=>{const p=panel();assert.equal(compare(obs(p,'hyperion:cost'),obs(p,'hyperion:regional-plan'),p).status,'NOT_COMPARABLE');});
test('power generation and campus capacity cannot be compared or added',()=>{const p=panel();assert.equal(compare(obs(p,'hyperion:power-gas'),obs(p,'hyperion:planned-capacity'),p).status,'NOT_COMPARABLE');assert.throws(()=>assertAddable([obs(p,'hyperion:power-gas'),obs(p,'hyperion:cost')]),/DO_NOT_ADD/);});
test('categorical status comparison is limited by source dates; no numeric ranking',()=>{const p=panel();const a=obs(p,'hyperion:status'),z=p.observations.find(o=>o.projectId==='aws-warren'&&o.metricId==='PROJECT_STATUS');assert.equal(compare(a,z,p).status,'LIMITED_COMPARABILITY');assert.equal(compare(a,a,p).status,'COMPARABLE');});
test('cross-company accounting, finance and power comparisons reject incompatible entities/scopes',()=>{const p=panel();for(const [a,z] of [['hyperion:equity-2026','fairwater:site-PP&E'],['hyperion:offering','polaris-forge-1:p-notes250-principal'],['hyperion:power-gas','fairwater:solar']])assert.equal(compare(obs(p,a),obs(p,z),p).status,'NOT_COMPARABLE');});
test('every non-null within-project monetary pair has a machine-readable anti-addition edge',()=>{const p=panel();assert.equal(p.overlaps.aggregationAllowed,false);assert.ok(p.overlaps.DO_NOT_ADD_PAIRS.length>=77);assert.throws(()=>assertAddable(p.financing),/DO_NOT_ADD/);});
test('manager is not fund owner and proposed ElPaso terms are not closed legal ownership',()=>{const b=fresh(),p=panel();assert.equal(claim(b,'hyperion:ownership-blue-owl-funds').entityId,'blue-owl-funds');assert.ok(p.relationships.filter(r=>r.projectId==='el-paso'&&r.relationshipType==='PARTIALLY_OWNS').every(r=>r.relationshipState==='PROPOSED'));assert.ok(p.observations.filter(o=>o.projectId==='el-paso'&&/INTEREST/.test(o.metricId)).every(o=>o.condition&&o.publicationEligibility!=='PUBLIC_READY'));});
test('Jupiter design changes retain original source, revised design and native dates',()=>{const p=panel(),rs=p.observations.filter(o=>o.projectId==='jupiter'&&o.metricId==='POWER_DESIGN');assert.equal(rs.length,2);assert.ok(rs.some(o=>o.value==='BEHIND_METER_NATURAL_GAS_MICROGRID'&&o.recordState==='SUPERSEDED'));assert.ok(rs.some(o=>o.value==='BLOOM_FUEL_CELL_MICROGRID'&&o.recordState==='CURRENT'));});
test('registered source vintage links retain exact hashes and clocks',()=>{const p=panel();for(const o of p.observations)for(let i=0;i<o.sourceIds.length;i++){const s=p.sources.find(s=>s.sourceId===o.sourceIds[i]);assert.equal(o.sourceVersions[i],s.sourceVersion);assert.equal(o.sourceHashes[i],s.sourceHash);assert.equal(o.documentDates[i],s.documentDate);}});
test('economic identity excludes retrieval timestamps/access diagnostics and working path',()=>{const a=fresh(),b=fresh();for(const s of b.sources){s.retrievedAt='2099-01-01T00:00:00Z';s.accessError='transient';s.retrievalStatus='FAILED';}assert.deepEqual(panel(a),panel(b));});
test('changed claim and definition or source hash changes panel identity',()=>{const a=fresh(),b=fresh();claim(b,'hyperion:cost').value=27.1;assert.notEqual(panel(a).panelHash,panel(b).panelHash);const s=b.sources.find(s=>s.sourceId==='cc-pimco');s.sourceHash='a'.repeat(64);s.sourceVersion=s.sourceId+'@'+s.sourceHash;assert.notEqual(panel(a).panelHash,panel(b).panelHash);});
test('same-source revision uses a distinct immutable record; same-period restatement keeps original',()=>{const b=fresh();const orig=claim(b,'hyperion:equity-2025'),src=b.sources.find(s=>s.sourceId==='meta-2025k');const s={...src,sourceId:'meta-2025k-recast',sourceFamilyId:src.sourceFamilyId,sourceHash:'b'.repeat(64),sourceVersion:'meta-2025k-recast@'+'b'.repeat(64),documentDate:'2026-10-07',availableFrom:'2026-10-07',qualificationStatus:'ARCHIVED_REVIEWED',byteSize:100,previousSourceVersion:src.sourceVersion};b.sources.push(s);b.claims.push({...orig,claimId:'hyperion:equity-2025-restated',sourceIds:[s.sourceId],value:1.9,previousClaimId:orig.claimId,recordState:'RESTATED'});const p=panel(b);assert.equal(obs(p,orig.claimId).value,1.83);assert.equal(obs(p,orig.claimId).recordState,'SUPERSEDED');assert.equal(obs(p,'hyperion:equity-2025-restated').value,1.9);assert.equal(obs(p,'hyperion:equity-2025-restated').recordState,'RESTATED');});
test('missingness is a denominator with family-specific caveats, not a score',()=>{const p=panel();assert.ok(p.views.missingness.every(m=>m.denominator===11&&m.coveragePercent>=0&&m.coveragePercent<=100));assert.equal(p.views.missingness.find(m=>m.fieldFamily==='legalOwner').withAtLeastOneQualifiedField,0);assert.ok(p.views.companyCoverage.find(c=>c.companyId==='GOOG').majorSourceGaps.includes('financing'));});
test('PUBLIC_READY requires archived, primary, unconflicted, low-overlap direct evidence',()=>{const p=panel();for(const o of p.observations.filter(o=>o.publicationEligibility==='PUBLIC_READY')){assert.equal(o.evidenceClass,'PRIMARY_VERIFIED');assert.equal(o.qualificationStatus,'QUALIFIED');assert.equal(o.overlapStatus,'NO_KNOWN_OVERLAP');assert.equal(o.condition,null);assert.ok(o.sourceHashes.every(Boolean));assert.equal(o.unit.startsWith('USD_'),false);}assert.equal(obs(p,'hyperion:maximum-exposure-2026').publicationEligibility,'REVIEW_REQUIRED');assert.equal(obs(p,'hyperion:financed-capacity').publicationEligibility,'REVIEW_REQUIRED');});
test('conflicting Fairwater conclusion stays review-required and no historical claim overwritten',()=>{const p=panel();assert.equal(obs(p,'fairwater:status').recordState,'CONFLICT_REQUIRES_REVIEW');assert.equal(obs(p,'fairwater:status').publicationEligibility,'REVIEW_REQUIRED');assert.equal(obs(p,'fairwater:status').value,'PARTIALLY_OPERATIONAL');});
test('project-recognized AI revenue remains unavailable; no capacity/revenue allocation',()=>{const p=panel();assert.ok(p.observations.filter(o=>/AI_REVENUE|RECOGNIZED_AI_REVENUE/.test(o.metricId)).every(o=>o.value===null));assert.ok(p.views.projectCapitalStructure.every(v=>v.noDollarTotal));});
const mutations=[
 ['duplicate project',b=>b.projects.push(b.projects[0]),/duplicate stable ID|duplicate physical|duplicate array item/],
 ['duplicate entity',b=>b.entities.push(b.entities[0]),/duplicate stable ID|duplicate array item/],
 ['duplicate physical identity',b=>b.projects[1].assetIdentity=b.projects[0].assetIdentity,/duplicate physical/],
 ['unknown entity',b=>claim(b,'hyperion:cost').entityId='nope',/unknown entities/],
 ['missing source',b=>claim(b,'hyperion:cost').sourceIds=[],/provenance/],
 ['unknown scope',b=>claim(b,'hyperion:cost').scopeId='nope',/unknown scopes/],
 ['currency mismatch',b=>claim(b,'hyperion:cost').currency='EUR',/currency\/unit/],
 ['invalid unit',b=>claim(b,'hyperion:cost').unit='BOTTLES',/invalid native unit/],
 ['ownership over100',b=>claim(b,'hyperion:ownership-meta').value=110,/percentage|ownership/],
 ['fund manager mistaken for owner',b=>claim(b,'hyperion:ownership-blue-owl-funds').entityId='blue-owl-manager',/manager not owner/],
 ['planned capacity operational relabel',b=>{const c=claim(b,'hyperion:planned-capacity');c.field='operational-capacity';c.capacityDefinition='CAMPUS_PLANNED';},/planned capacity mislabeled/],
 ['estimated cost observed relabel',b=>claim(b,'hyperion:cost').observedOrEstimated='OBSERVED_REPORTED',/estimated cost falsely/],
 ['secondary primary upgrade',b=>claim(b,'hyperion:financed-capacity').evidenceClass='PRIMARY_VERIFIED',/secondary upgraded/],
 ['zero fills missing field',b=>claim(b,'hyperion:debt-coupon').value=0,/UNAVAILABLE fabricated/],
 ['unsupported relation',b=>b.relationships[0].relationshipType='LENDS_TO',/unsupported relationship/],
 ['duplicated instrument',b=>b.financing.push({...b.financing[0],id:'other'}),/instrument\/obligation duplicated/],
 ['unknown archetype',b=>b.projects[0].primaryArchetype='BEST_FUNDED',/unknown archetype/],
 ['AI ROI field',b=>b.projects[0].aiRoi=1,/prohibited|unexpected/],
 ['hidden leverage field',b=>b.projects[0].hiddenDebt=1,/prohibited|unexpected/],
 ['systemic risk score',b=>b.projects[0].systemicRiskScore=1,/prohibited|unexpected/],
 ['aggregate investment',b=>b.totalAiInvestment=1,/prohibited|unexpected/],
 ['future actual operational date',b=>b.projects[0].actualOperationalDate='2028-01-01',/future actual/],
];
for(const [name,mutate,rx]of mutations)test(name,()=>bad(mutate,rx));
test('future observed effective period fails; future guidance is allowed explicitly',()=>bad(b=>claim(b,'hyperion:equity-2026').effectiveDate='2027-01-01',/future observation/));
test('operational before construction inconsistency is rejected',()=>{const b=fresh();const c=claim(b,'fairwater:status');c.effectiveDate='2024-01-01';assert.throws(()=>panel(b),/operational before construction/);});
test('unknown definition, duplicate observation and source-vintage corruption rejected',()=>{invalid(p=>p.observations[0].definitionId='missing',/unknown observation reference/);invalid(p=>p.observations.push(p.observations[0]),/duplicate observation/);invalid(p=>p.observations[0].sourceHashes=['f'.repeat(64)],/source vintage/);});
test('future source injection and PUBLIC_READY escalation rejected',()=>{invalid(p=>p.observations[0].availableFrom='2027-01-01',/future source/);invalid(p=>obs(p,'hyperion:offering').publicationEligibility='PUBLIC_READY',/publication eligibility/);});
test('missing anti-addition and synthetic derived values rejected',()=>{invalid(p=>p.overlaps.DO_NOT_ADD_PAIRS.pop(),/DO_NOT_ADD missing/);invalid(p=>p.views.companyCoverage[0].qualifiedObservations=999,/derived views/);});
test('fresh-process rebuild is byte stable in different working directories',()=>{const command=path.join(root,'scripts/build-panel.mjs'),args=[command,'--as-of',ASOF];assert.deepEqual(execFileSync(process.execPath,args,{cwd:'/tmp'}),execFileSync(process.execPath,args,{cwd:root}));});
test('Phase3A and Phase3B frozen evidence and production paths remain byte unchanged',()=>{const prefix='research/ai-infrastructure-financing/';const paths=['src','public','data','scripts','.github','package.json','package-lock.json','research/ai-capex-monetization','research/signal-engine',...['data','cases','hydration','phase3b','schemas','scripts','reports/phase3a-foundation-qualification.json','reports/phase3b-qualification.json','reports/hyperion-scope-reconciliation.json','tests/foundation.test.mjs','tests/phase3b.test.mjs'].map(s=>prefix+s)];const changed=execFileSync('git',['diff','--name-only','940be50f61a1516482da936a38f10a62cf262b5a','--',...paths],{encoding:'utf8'});assert.equal(changed.trim(),'');});
test('invalid evidence classification fails schema instead of upgrading a value',()=>bad(b=>claim(b,'hyperion:cost').evidenceClass='PRIMARY_GUESSED',/invalid enum/));
test('explicit incompatible scope veto wins over a comparison allow-list',()=>{const p=panel(),a=obs(p,'hyperion:planned-capacity');p.scopes.find(s=>s.scopeId===a.scopeId).notComparableTo.push(a.scopeId);assert.equal(compare(a,a,p).status,'NOT_COMPARABLE');});
test('non-USD native money retains anti-addition protection without FX conversion',()=>{const b=fresh(),c=claim(b,'hyperion:cost');c.unit='EUR_BILLION';c.currency='EUR';const p=panel(b),o=obs(p,c.claimId);assert.ok(p.overlaps.DO_NOT_ADD_PAIRS.some(pair=>pair.leftObservationId===o.observationId||pair.rightObservationId===o.observationId));assert.equal(compare(o,obs(p,'hyperion:offering'),p).status,'NOT_COMPARABLE');});
test('undated status source has unknown report date separate from availability clock',()=>{const p=panel();assert.equal(p.statusHistory.find(h=>h.projectId==='abilene').reportedAt,null);});
test('publication or review date does not manufacture a project announcement date',()=>{const p=panel();for(const id of ['quincy','aws-canton','jupiter'])assert.equal(p.projects.find(x=>x.id===id).announcedAt,null);});
test('repeat research writes are byte stable and immutable collision cannot replace current artifacts',()=>{const p=panel();writePanel(p);const files=['observations','projects','entities','relationships','definitions','scopes','claims','overlaps','status-history','methodology','derived-views'];const bytes=()=>files.map(name=>fs.readFileSync(path.join(root,name+'.json'),'utf8'));const before=bytes();writePanel(p);assert.deepEqual(bytes(),before);const corrupted=structuredClone(p);corrupted.observations[0].value='corrupt';assert.throws(()=>writePanel(corrupted),/Immutable snapshot identity collision/);assert.deepEqual(bytes(),before);});
